<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LowonganModelSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $lowongan = [
            // LW001 - IT/System Development Intern (Backend - VB.NET & MySQL)
            [
                'lowongan_id'    => 'LW001',
                'perusahaan_id'  => 'P001',
                'posisi'         => 'IT/System Development Intern',
                'deskripsi'      => 'Membantu pengembangan dan pemeliharaan sistem informasi internal perusahaan menggunakan VB.NET dan MySQL. Terlibat dalam analisis kebutuhan, implementasi fitur baru, serta perbaikan bug pada sistem yang berjalan. Membuat dokumentasi teknis dan laporan pengembangan sistem secara berkala.',
                'tools'          => 'Visual Basic / VB.NET, MySQL, atau teknologi web sesuai kebutuhan proyek',
                'skill'          => 'Pemrograman dasar, logika sistem, komunikasi, kemampuan analisis',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW002 - Backend Engineer
            [
                'lowongan_id'    => 'LW002',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'Backend Engineer',
                'deskripsi'      => 'Mengembangkan dan memelihara layanan REST API menggunakan Laravel atau FastAPI sebagai fondasi sistem SIPP lingkungan hidup. Melakukan integrasi data antar modul sistem, pengelolaan database MySQL/PostgreSQL, serta konfigurasi API gateway dan koneksi ke layanan cloud. Mendokumentasikan endpoint API menggunakan Postman dan menyusun catatan perubahan teknis.',
                'tools'          => 'Laravel/FastAPI, MySQL/PostgreSQL, Docker, REST API, Postman',
                'skill'          => 'REST API, database management, system integration',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW003 - Frontend Engineer
            [
                'lowongan_id'    => 'LW003',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'Frontend Engineer',
                'deskripsi'      => 'Mengembangkan antarmuka dashboard sistem SIPP yang responsif dan mudah digunakan menggunakan React atau Vue.js. Melakukan integrasi frontend dengan REST API backend dan menerapkan visualisasi data lingkungan hidup secara interaktif. Memastikan konsistensi tampilan dan pengalaman pengguna sesuai desain yang telah ditetapkan.',
                'tools'          => 'React/Vue, JavaScript',
                'skill'          => 'UI/UX, data visualization',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW004 - AI Engineer
            [
                'lowongan_id'    => 'LW004',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Membangun pipeline pemrosesan data untuk kebutuhan AI/LLM seperti DeepSeek, Qwen, dan Llama dalam sistem SIPP. Melakukan preprocessing data lingkungan, eksplorasi model, dan integrasi hasil prediksi ke dalam sistem. Mendokumentasikan eksperimen model dan menyusun laporan performa pipeline AI.',
                'tools'          => 'Python, TensorFlow/PyTorch, LLM tools',
                'skill'          => 'Machine learning, data processing',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW005 - System Analyst
            [
                'lowongan_id'    => 'LW005',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis kebutuhan sistem bersama stakeholder dan menyusun dokumen SRS (Software Requirements Specification) secara terstruktur. Membuat diagram alur sistem, use case diagram, dan spesifikasi fungsional menggunakan tools seperti draw.io. Melaksanakan pengujian fungsional sistem dan mendokumentasikan hasil testing serta rekomendasi perbaikan.',
                'tools'          => 'draw.io, Postman',
                'skill'          => 'Analisis sistem, software testing, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW006 - Data Engineer
            [
                'lowongan_id'    => 'LW006',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Membangun pipeline ETL untuk mengolah data spasial dan non-spasial dalam format CSV, SHP, dan GeoJSON ke dalam database PostGIS. Melakukan integrasi dataset dari berbagai sumber dan memastikan kualitas serta konsistensi data geospasial yang tersimpan. Mendokumentasikan proses pipeline data dan membuat laporan validasi dataset secara rutin.',
                'tools'          => 'PostGIS, Python (FastAPI), AWS, Docker, CI/CD tools',
                'skill'          => 'ETL, GIS, database, Python, machine learning, cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW007 - Backend Developer
            [
                'lowongan_id'    => 'LW007',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan endpoint API menggunakan Python FastAPI untuk mendukung platform WebGIS Satu Peta Jawa Timur. Melakukan integrasi layanan GIS, implementasi logika bisnis pada sisi server, serta pengelolaan query data spasial di PostGIS. Menyusun dokumentasi API dan memastikan performa endpoint sesuai standar yang ditetapkan.',
                'tools'          => 'PostGIS, Python (FastAPI), AWS, Docker, CI/CD tools',
                'skill'          => 'Python, REST API, FastAPI, machine learning, cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW008 - Frontend Developer
            [
                'lowongan_id'    => 'LW008',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun dashboard peta interaktif menggunakan OpenLayers atau Leaflet.js untuk visualisasi data geospasial Jawa Timur. Mengintegrasikan komponen WebGIS dengan REST API backend dan memastikan tampilan responsif di berbagai perangkat. Membuat dokumentasi komponen frontend dan panduan penggunaan fitur peta.',
                'tools'          => 'JavaScript, OpenLayers/Leaflet',
                'skill'          => 'JavaScript, WebGIS',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW009 - AI & Data Engineer
            [
                'lowongan_id'    => 'LW009',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'AI & Data Engineer',
                'deskripsi'      => 'Mengeksplorasi dan mengembangkan model AI/LLM untuk kebutuhan metadata otomatis dan prediksi data geospasial. Membangun pipeline pemrosesan data menggunakan Python dan mengintegrasikan hasil model ke dalam sistem Platform Satu Peta. Mendokumentasikan eksperimen, hasil evaluasi model, dan rekomendasi pengembangan lanjutan.',
                'tools'          => 'PostGIS, Python (FastAPI), AWS, Docker, CI/CD tools',
                'skill'          => 'ETL, GIS, database, Python, machine learning, cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW010 - DevOps Engineer
            [
                'lowongan_id'    => 'LW010',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola proses deployment aplikasi WebGIS ke lingkungan cloud AWS menggunakan Docker dan CI/CD pipeline. Melakukan containerization layanan, konfigurasi monitoring sistem, serta memastikan ketersediaan dan performa infrastruktur. Menyusun dokumentasi deployment dan runbook penanganan insiden.',
                'tools'          => 'AWS, Docker, CI/CD tools',
                'skill'          => 'Cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW011 - Blockchain Engineer
            [
                'lowongan_id'    => 'LW011',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Blockchain Engineer',
                'deskripsi'      => 'Mengembangkan smart contract menggunakan Hyperledger Fabric dan melakukan integrasi middleware blockchain ke dalam sistem backend. Membangun dan menguji chaincode, serta mendokumentasikan arsitektur jaringan blockchain dan alur transaksi. Berkolaborasi dengan tim backend untuk memastikan integrasi berjalan sesuai spesifikasi.',
                'tools'          => 'Hyperledger Fabric, Python, Node.js, SQL, Docker, AWS',
                'skill'          => 'Distributed systems, smart contract, REST API, microservices',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW012 - Backend Developer
            [
                'lowongan_id'    => 'LW012',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan REST API dan microservices menggunakan Python atau Node.js untuk mendukung sistem berbasis blockchain di PT ARM Solusi. Merancang dan mengimplementasikan data pipeline, mengelola database SQL, serta mendokumentasikan arsitektur layanan backend. Berkolaborasi dengan tim DevOps untuk deployment menggunakan Docker dan AWS.',
                'tools'          => 'Python, Node.js, SQL, Docker, AWS',
                'skill'          => 'REST API, microservices, data engineering, log analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW013 - Data Engineer
            [
                'lowongan_id'    => 'LW013',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Melakukan preprocessing dan analisis log transaksi blockchain untuk kebutuhan audit data dan pelaporan. Membangun pipeline data menggunakan Python, melakukan validasi integritas data, dan menyajikan hasil analisis dalam bentuk laporan visual. Mendokumentasikan proses ETL dan menyusun catatan temuan audit secara berkala.',
                'tools'          => 'Python, SQL, Grafana, Prometheus',
                'skill'          => 'Data engineering, log analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW014 - Frontend Engineer
            [
                'lowongan_id'    => 'LW014',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Frontend Engineer',
                'deskripsi'      => 'Mengembangkan dashboard visualisasi log transaksi dan verifikasi data blockchain menggunakan React. Mengintegrasikan komponen frontend dengan API backend dan menampilkan data audit secara real-time. Membuat dokumentasi komponen UI dan panduan penggunaan dashboard bagi pengguna internal.',
                'tools'          => 'Node.js / React',
                'skill'          => 'Web dev, UI/UX',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW015 - AI Engineer
            [
                'lowongan_id'    => 'LW015',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Membangun dan mengoptimalkan pipeline ML serta mengintegrasikan model LLM seperti DeepSeek dan Qwen ke dalam sistem PT ARM Solusi. Melakukan eksperimen, evaluasi performa model, dan penyesuaian prompt engineering sesuai kebutuhan bisnis. Mendokumentasikan hasil eksperimen dan menyusun laporan rekomendasi model terbaik.',
                'tools'          => 'Python, Grafana, Prometheus',
                'skill'          => 'ML pipeline, LLM',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW016 - Full-stack
            [
                'lowongan_id'    => 'LW016',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Full-stack',
                'deskripsi'      => 'Mengembangkan aplikasi fullstack AI Workspace dari sisi frontend hingga backend menggunakan React dan Python. Mengintegrasikan modul AI ke dalam antarmuka pengguna dan memastikan alur data berjalan optimal antar layanan. Menyusun dokumentasi teknis end-to-end dan melakukan pengujian integrasi sistem.',
                'tools'          => 'Python, Node.js / React, SQL, Docker, AWS',
                'skill'          => 'REST API, microservices, web dev, UI/UX, ML pipeline, LLM',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW017 - DevOps
            [
                'lowongan_id'    => 'LW017',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'DevOps',
                'deskripsi'      => 'Mengelola proses deployment, containerization dengan Docker, dan konfigurasi infrastruktur cloud AWS untuk sistem PT ARM Solusi. Membangun dan memelihara pipeline CI/CD, melakukan monitoring menggunakan Grafana dan Prometheus, serta merespons insiden infrastruktur. Mendokumentasikan konfigurasi deployment dan prosedur operasional standar.',
                'tools'          => 'Docker, AWS, Grafana, Prometheus',
                'skill'          => 'Docker, CI/CD, cloud',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW018 - Data Engineer (batch 2)
            [
                'lowongan_id'    => 'LW018',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Membangun pipeline ETL untuk mengolah data spasial dan non-spasial batch kedua Platform Satu Peta Jatim, termasuk harmonisasi dataset dan manajemen PostGIS. Melakukan validasi kualitas data geospasial dan memastikan konsistensi format antar dataset yang terintegrasi. Mendokumentasikan proses pipeline dan membuat laporan status data secara berkala.',
                'tools'          => 'PostGIS, Python (FastAPI), AWS, Docker, CI/CD tools',
                'skill'          => 'ETL, GIS, Python, machine learning, cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW019 - Backend Developer (batch 2)
            [
                'lowongan_id'    => 'LW019',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan endpoint API menggunakan FastAPI untuk mendukung layanan batch kedua Platform Satu Peta Jatim. Melakukan integrasi layanan GIS, optimasi query PostGIS, dan pemeliharaan logika bisnis pada sisi server. Menyusun dokumentasi API dan laporan pengembangan fitur backend secara rutin.',
                'tools'          => 'PostGIS, Python (FastAPI), AWS, Docker, CI/CD tools',
                'skill'          => 'ETL, GIS, Python, REST API, machine learning, cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW020 - Frontend Developer (batch 2)
            [
                'lowongan_id'    => 'LW020',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun dashboard WebGIS interaktif menggunakan OpenLayers atau Leaflet.js untuk batch kedua Platform Satu Peta Jatim. Mengintegrasikan komponen peta dengan REST API dan memastikan performa rendering data geospasial secara real-time. Membuat dokumentasi komponen frontend dan panduan teknis pengembangan peta.',
                'tools'          => 'JavaScript, OpenLayers/Leaflet',
                'skill'          => 'JavaScript, WebGIS',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW021 - AI & Data Engineer (batch 2)
            [
                'lowongan_id'    => 'LW021',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'AI & Data Engineer',
                'deskripsi'      => 'Mengeksplorasi model AI untuk prediksi geospasial dan membangun pipeline pemrosesan data batch kedua Platform Satu Peta Jatim. Melakukan evaluasi model, integrasi hasil prediksi ke dalam sistem, dan mendokumentasikan eksperimen secara terstruktur. Berkolaborasi dengan tim data untuk memastikan kualitas input dan output model.',
                'tools'          => 'PostGIS, Python (FastAPI), AWS, Docker, CI/CD tools',
                'skill'          => 'ETL, GIS, Python, machine learning, cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW022 - DevOps Engineer
            [
                'lowongan_id'    => 'LW022',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'DevOps Engineer (Cloud & On-Premise)',
                'deskripsi'      => 'Mengelola deployment batch kedua Platform Satu Peta Jatim pada infrastruktur hybrid cloud AWS dan on-premise. Mengkonfigurasi containerization, pipeline CI/CD, monitoring sistem, serta memastikan ketersediaan layanan secara konsisten. Menyusun dokumentasi arsitektur infrastruktur dan runbook operasional.',
                'tools'          => 'AWS, Docker, CI/CD tools',
                'skill'          => 'Cloud computing, CI/CD',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW023 - Backend Developer
            [
                'lowongan_id'    => 'LW023',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan fitur backend sistem ERP-BPM Sarastya menggunakan Laravel atau Node.js, termasuk implementasi REST API dan pengelolaan database. Melakukan integrasi antar modul sistem dan memastikan performa layanan backend sesuai kebutuhan klien. Mendokumentasikan endpoint API dan menyusun catatan perubahan teknis secara berkala.',
                'tools'          => 'ERP-BPM platform, Laravel/Node.js',
                'skill'          => 'Web development, server management',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW024 - Frontend Developer
            [
                'lowongan_id'    => 'LW024',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun antarmuka web dan mobile sistem ERP-BPM menggunakan React atau framework modern yang responsif. Melakukan integrasi frontend dengan REST API backend dan memastikan pengalaman pengguna yang konsisten di berbagai perangkat. Membuat dokumentasi komponen UI dan panduan penggunaan fitur bagi end user.',
                'tools'          => 'ERP-BPM platform, React',
                'skill'          => 'Web development, mobile development',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW025 - Full Stack Developer
            [
                'lowongan_id'    => 'LW025',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Full Stack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi web dan mobile end-to-end pada sistem ERP-BPM Sarastya dari sisi frontend maupun backend. Melakukan integrasi modul, pengelolaan state aplikasi, dan pemeliharaan API yang sudah berjalan. Menyusun dokumentasi teknis fullstack dan melakukan pengujian integrasi secara menyeluruh.',
                'tools'          => 'ERP-BPM platform, Laravel/Node.js/React',
                'skill'          => 'Web development, mobile development, server management',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW026 - DevOps
            [
                'lowongan_id'    => 'LW026',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'DevOps',
                'deskripsi'      => 'Mengelola deployment dan pemeliharaan server sistem ERP-BPM Sarastya, termasuk konfigurasi environment dan monitoring performa. Melakukan troubleshooting infrastruktur, pengelolaan dependensi layanan, dan memastikan uptime sistem. Mendokumentasikan konfigurasi server dan prosedur operasional harian.',
                'tools'          => 'ERP-BPM platform, Cisco/Mikrotik',
                'skill'          => 'IT governance, networking, server management',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW027 - Data Analyst
            [
                'lowongan_id'    => 'LW027',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Menganalisis data klien pada sistem ERP-BPM menggunakan Power BI dan Python untuk menghasilkan insight yang actionable. Membuat laporan visualisasi data, dashboard performa bisnis, dan rekomendasi berbasis data bagi manajemen klien. Mendokumentasikan metodologi analisis dan menyusun template laporan standar.',
                'tools'          => 'Python, Power BI',
                'skill'          => 'Data analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW028 - Business Analyst
            [
                'lowongan_id'    => 'LW028',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Business Analyst',
                'deskripsi'      => 'Menganalisis data pemasaran dan penjualan klien untuk mendukung pengambilan keputusan bisnis berbasis data pada sistem ERP-BPM. Menyusun laporan analisis bisnis, melakukan identifikasi tren pasar, dan memberikan rekomendasi strategis yang terukur. Mendokumentasikan temuan analisis dan mempresentasikan hasil kepada stakeholder terkait.',
                'tools'          => 'ERP-BPM platform, Power BI',
                'skill'          => 'Business analysis, data analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW029 - E-Governance
            [
                'lowongan_id'    => 'LW029',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'E-Governance',
                'deskripsi'      => 'Membantu implementasi tata kelola TI dan kebijakan e-governance pada sistem ERP-BPM di lingkungan klien Sarastya. Menyusun dokumentasi prosedur operasional, melakukan gap analysis terhadap regulasi yang berlaku, dan mendukung audit internal sistem. Berkolaborasi dengan tim teknis untuk memastikan kepatuhan sistem terhadap standar yang ditetapkan.',
                'tools'          => 'ERP-BPM platform',
                'skill'          => 'IT governance, business analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW030 - Network Engineer
            [
                'lowongan_id'    => 'LW030',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Network Engineer',
                'deskripsi'      => 'Melakukan pemeliharaan server dan memastikan keamanan jaringan pada infrastruktur klien Sarastya Agility Innovations. Mengkonfigurasi perangkat jaringan Cisco/Mikrotik, melakukan monitoring trafik, dan menangani gangguan konektivitas. Mendokumentasikan topologi jaringan dan prosedur penanganan insiden jaringan.',
                'tools'          => 'Cisco/Mikrotik',
                'skill'          => 'Networking, server management',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW031 - Frontend Developer
            [
                'lowongan_id'    => 'LW031',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web yang responsif dan user-friendly menggunakan React atau Next.js untuk proyek klien PT Time Door Indonesia. Melakukan implementasi desain UI/UX ke dalam komponen frontend, integrasi dengan REST API, dan optimasi performa halaman. Membuat dokumentasi komponen dan melakukan code review bersama tim.',
                'tools'          => 'React/Next.js',
                'skill'          => 'HTML/CSS/JavaScript, React/Next.js',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW032 - QA Tester
            [
                'lowongan_id'    => 'LW032',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'QA Tester',
                'deskripsi'      => 'Melakukan pengujian fungsional dan otomatis pada aplikasi web dan mobile menggunakan Playwright atau Selenium. Menyusun test case, mendokumentasikan temuan bug, serta berkoordinasi dengan developer untuk proses perbaikan. Membuat laporan hasil testing secara berkala dan memastikan kualitas produk sebelum dirilis.',
                'tools'          => 'Playwright/Selenium',
                'skill'          => 'Software testing, automation testing',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW033 - AI Engineer
            [
                'lowongan_id'    => 'LW033',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Mengimplementasikan modul AI ke dalam sistem klien PT Time Door menggunakan Python dan framework TensorFlow atau PyTorch. Melakukan preprocessing data, pelatihan model, dan integrasi hasil prediksi ke dalam aplikasi yang berjalan. Mendokumentasikan pipeline AI dan menyusun laporan evaluasi performa model.',
                'tools'          => 'Python, TensorFlow/PyTorch',
                'skill'          => 'Python, ML framework',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW034 - DevOps Engineer
            [
                'lowongan_id'    => 'LW034',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola proses deployment aplikasi ke cloud AWS atau GCP menggunakan Docker dan pipeline CI/CD di PT Time Door Indonesia. Mengkonfigurasi environment staging dan production, melakukan monitoring performa sistem, serta menangani insiden infrastruktur. Menyusun dokumentasi deployment dan runbook operasional tim.',
                'tools'          => 'Docker, AWS/GCP',
                'skill'          => 'Docker, CI/CD, cloud',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW035 - Mobile Developer (Flutter)
            [
                'lowongan_id'    => 'LW035',
                'perusahaan_id'  => 'P007',
                'posisi'         => 'Mobile Developer (Flutter)',
                'deskripsi'      => 'Mengembangkan fitur aplikasi mobile cross-platform menggunakan Flutter dan Dart untuk produk Maxchat. Melakukan integrasi dengan REST API backend, implementasi state management, dan pengujian UI di berbagai perangkat. Mendokumentasikan komponen Flutter dan menyusun catatan changelog untuk setiap rilis fitur.',
                'tools'          => 'Flutter, Dart, Postman',
                'skill'          => 'Flutter/Dart, REST API, pemecahan masalah',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW036 - Backend Developer
            [
                'lowongan_id'    => 'LW036',
                'perusahaan_id'  => 'P007',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun dan memelihara layanan API backend menggunakan Node.js atau Go untuk mendukung platform Maxchat. Melakukan pengelolaan database, implementasi logika bisnis, dan integrasi dengan layanan WhatsApp Business API. Mendokumentasikan endpoint API menggunakan Postman dan menyusun catatan teknis perubahan sistem.',
                'tools'          => 'Node.js/Go (backend), Postman',
                'skill'          => 'Backend development, REST API, pemecahan masalah',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW037 - QA Automation
            [
                'lowongan_id'    => 'LW037',
                'perusahaan_id'  => 'P007',
                'posisi'         => 'QA Automation',
                'deskripsi'      => 'Menyusun dan mengeksekusi skenario pengujian otomatis menggunakan Playwright atau Cypress untuk aplikasi Maxchat. Mengidentifikasi dan mendokumentasikan bug, membuat laporan hasil testing, serta berkolaborasi dengan tim developer untuk verifikasi perbaikan. Memelihara dan memperbarui skrip pengujian sesuai perkembangan fitur.',
                'tools'          => 'automation tools (Playwright/Cypress)',
                'skill'          => 'Automation testing, pemecahan masalah',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW038 - Programmer
            [
                'lowongan_id'    => 'LW038',
                'perusahaan_id'  => 'P008',
                'posisi'         => 'Programmer',
                'deskripsi'      => 'Mengembangkan fitur baru dan memperbaiki bug pada aplikasi berbasis Flutter atau web di Politeknik Batu. Melakukan integrasi dengan API, pengelolaan state aplikasi, dan pengujian fungsional fitur yang dikembangkan. Mendokumentasikan perubahan kode dan menyusun laporan progres pengembangan secara rutin.',
                'tools'          => 'Flutter, Laravel/PHP, MySQL, Postman',
                'skill'          => 'Pemrograman dasar (Flutter/web), API, database, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW039 - Quality Assurance (QA)
            [
                'lowongan_id'    => 'LW039',
                'perusahaan_id'  => 'P008',
                'posisi'         => 'Quality Assurance (QA)',
                'deskripsi'      => 'Melakukan pengujian fungsional aplikasi Flutter dan web milik Politeknik Batu secara menyeluruh berdasarkan test case yang telah disusun. Mendokumentasikan temuan bug lengkap dengan langkah reproduksi dan tingkat keparahan, serta memverifikasi hasil perbaikan dari developer. Membuat laporan QA mingguan dan menyusun rekomendasi peningkatan kualitas.',
                'tools'          => 'Postman, tools pengujian (manual testing)',
                'skill'          => 'Software testing, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW040 - Tester
            [
                'lowongan_id'    => 'LW040',
                'perusahaan_id'  => 'P008',
                'posisi'         => 'Tester',
                'deskripsi'      => 'Melaksanakan pengujian manual aplikasi internal Politeknik Batu dengan menyusun skenario uji dan test case yang komprehensif. Mendokumentasikan hasil pengujian, mencatat temuan defect, dan berkoordinasi dengan tim pengembang untuk proses perbaikan. Membuat laporan testing akhir sebagai dasar keputusan rilis aplikasi.',
                'tools'          => 'Postman, tools pengujian (manual testing)',
                'skill'          => 'Software testing, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW041 - Game Programmer Intern
            [
                'lowongan_id'    => 'LW041',
                'perusahaan_id'  => 'P009',
                'posisi'         => 'Game Programmer Intern',
                'deskripsi'      => 'Mengimplementasikan fitur gameplay dan sistem game menggunakan Unity dan C# pada proyek game Ariverse Studio. Melakukan debugging, optimasi performa, dan profiling untuk memastikan game berjalan lancar di target platform. Mendokumentasikan arsitektur sistem game dan menyusun catatan teknis untuk anggota tim.',
                'tools'          => 'Unity, C#, Git',
                'skill'          => 'C#, Unity, OOP, Git',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW042 - Full Stack Developer Intern
            [
                'lowongan_id'    => 'LW042',
                'perusahaan_id'  => 'P009',
                'posisi'         => 'Full Stack Developer Intern',
                'deskripsi'      => 'Mengembangkan aplikasi web atau mobile fullstack menggunakan Flutter atau React untuk frontend dan Laravel atau ElysiaJS untuk backend. Merancang dan mengimplementasikan REST API, mengelola database relasional, serta melakukan pengujian integrasi. Mendokumentasikan arsitektur sistem dan menyusun panduan setup project untuk tim.',
                'tools'          => 'Flutter, React/Next.js, Laravel, MySQL, Git',
                'skill'          => 'Flutter/React, Laravel, REST API, database relasional',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW043 - Frontend Developer Intern
            [
                'lowongan_id'    => 'LW043',
                'perusahaan_id'  => 'P009',
                'posisi'         => 'Frontend Developer Intern',
                'deskripsi'      => 'Membangun antarmuka web yang responsif menggunakan React atau Next.js sesuai desain Figma yang telah disepakati tim Ariverse Studio. Melakukan integrasi komponen frontend dengan REST API, memastikan konsistensi UI, dan mengoptimalkan performa halaman. Membuat dokumentasi komponen dan melakukan review kode bersama senior developer.',
                'tools'          => 'React/Next.js, Figma, Git',
                'skill'          => 'HTML/CSS/JavaScript, React/Next.js, UI/UX dasar, Figma',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW044 - Data Analyst
            [
                'lowongan_id'    => 'LW044',
                'perusahaan_id'  => 'P010',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Menganalisis data Google Analytics, performa website, dan data media sosial Humas Polinema untuk menghasilkan insight komunikasi. Membuat visualisasi data menggunakan Looker Studio atau Tableau dan menyusun laporan insight secara berkala. Memberikan rekomendasi berbasis data untuk mendukung strategi komunikasi digital institusi.',
                'tools'          => 'Google Analytics, SQL, Python (Pandas, Matplotlib/Seaborn), Looker Studio / Tableau, Social Media Analytics Tools',
                'skill'          => 'Analisis data, visualisasi data, SQL, Python/R, interpretasi insight digital',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW045 - Social Media Analyst
            [
                'lowongan_id'    => 'LW045',
                'perusahaan_id'  => 'P010',
                'posisi'         => 'Social Media Analyst',
                'deskripsi'      => 'Menganalisis data engagement, reach, dan performa konten media sosial Humas Polinema menggunakan tools social media analytics. Menyusun laporan performa akun secara mingguan dan bulanan, serta memberikan rekomendasi strategi konten berbasis data. Mendokumentasikan tren dan pola audiens untuk mendukung perencanaan konten ke depan.',
                'tools'          => 'Google Analytics, SQL, Python (Pandas, Matplotlib/Seaborn), Looker Studio / Tableau, Social Media Analytics Tools',
                'skill'          => 'Analisis data, visualisasi data, SQL, Python/R, interpretasi insight digital',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW046 - Fullstack Developer (AI & Automation)
            [
                'lowongan_id'    => 'LW046',
                'perusahaan_id'  => 'P011',
                'posisi'         => 'Fullstack Developer (AI & Automation)',
                'deskripsi'      => 'Mengembangkan aplikasi fullstack yang terintegrasi dengan n8n untuk workflow automation dan WebSocket untuk komunikasi real-time. Membangun komponen frontend menggunakan React atau Next.js serta backend dengan Node.js atau Laravel, sekaligus mengintegrasikan AI chatbot berbasis LLM. Menyusun dokumentasi teknis sistem dan membuat diagram arsitektur integrasi layanan.',
                'tools'          => 'React/Next.js (frontend), Node.js/Laravel (backend), n8n, WebSocket, API AI (OpenAI/LLM), MySQL/PostgreSQL',
                'skill'          => 'Fullstack development, REST API, WebSocket, pemahaman dasar AI/chatbot, integrasi automation tools',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW047 - Fullstack JS Developer
            [
                'lowongan_id'    => 'LW047',
                'perusahaan_id'  => 'P012',
                'posisi'         => 'Fullstack JS Developer',
                'deskripsi'      => 'Mengembangkan fitur aplikasi web menggunakan JavaScript, Node.js, dan React atau Next.js pada proyek PT Utero Kreatif Indonesia. Melakukan integrasi frontend-backend, pengelolaan database PostgreSQL, dan memastikan performa serta skalabilitas aplikasi. Mendokumentasikan kode, menyusun catatan teknis, dan berpartisipasi dalam code review bersama tim.',
                'tools'          => 'JavaScript, Node.js, React/Next.js, Laravel/Express, MySQL/PostgreSQL, Git',
                'skill'          => 'Berpikir sistematis dan analitis, problem solving berbasis data, pemahaman kebutuhan bisnis, efisiensi & skalabilitas sistem',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW048 - Software Engineer
            [
                'lowongan_id'    => 'LW048',
                'perusahaan_id'  => 'P012',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Terlibat dalam analisis kebutuhan bisnis, perancangan arsitektur sistem, dan implementasi fitur berbasis web di PT Utero Kreatif Indonesia. Mengembangkan solusi teknis yang efisien dan terukur menggunakan stack JavaScript modern dengan pendekatan berbasis data. Menyusun dokumentasi teknis, ERD, dan spesifikasi sistem untuk keperluan pengembangan dan pemeliharaan.',
                'tools'          => 'JavaScript, Node.js, React/Next.js, Laravel/Express, MySQL/PostgreSQL, Git',
                'skill'          => 'Berpikir sistematis dan analitis, problem solving berbasis data, pemahaman kebutuhan bisnis, efisiensi & skalabilitas sistem',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW049 - Magang Perhotelan
            [
                'lowongan_id'    => 'LW049',
                'perusahaan_id'  => 'P013',
                'posisi'         => 'Magang Perhotelan (OJT) – berbagai departemen',
                'deskripsi'      => 'Menjalankan tugas operasional harian di berbagai departemen hotel sesuai penempatan, meliputi front office, housekeeping, atau food & beverage. Memberikan pelayanan tamu sesuai standar operasional The Himana Hotel dan belajar langsung dari supervisor lapangan. Menyusun laporan kegiatan magang harian dan mengikuti briefing operasional hotel secara rutin.',
                'tools'          => 'Sistem manajemen hotel (PMS), Microsoft Office (dasar)',
                'skill'          => 'Komunikasi baik, grooming, proaktif, detail, mampu bekerja tim maupun mandiri, disiplin',
                'ipk_min'        => null,
                'periode'        => 5,
                'insentif'       => 'Flexible',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW050 - Web Developer
            [
                'lowongan_id'    => 'LW050',
                'perusahaan_id'  => 'P014',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Memodifikasi dan mengembangkan sistem web Bidang Kerjasama Polinema menggunakan PHP atau Laravel sesuai kebutuhan pengguna. Melakukan perbaikan bug, penambahan fitur baru, dan memastikan antarmuka sistem mudah digunakan. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk administrator.',
                'tools'          => 'PHP/Laravel (web), MySQL/SQL Server',
                'skill'          => 'Web development (modifikasi sistem), manajemen data, SQL, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW051 - Data Engineer
            [
                'lowongan_id'    => 'LW051',
                'perusahaan_id'  => 'P014',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Mengelola dan mengorganisir penyimpanan dokumen digital kerjasama institusi Polinema menggunakan sistem database yang terstruktur. Melakukan klasifikasi, indexing, dan pemeliharaan integritas data dokumen di MySQL atau SQL Server. Menyusun dokumentasi prosedur pengelolaan data dan membuat laporan inventaris dokumen secara berkala.',
                'tools'          => 'MySQL/SQL Server, Python (data analysis)',
                'skill'          => 'Manajemen data, analisis data, SQL, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW052 - Data Analyst
            [
                'lowongan_id'    => 'LW052',
                'perusahaan_id'  => 'P014',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Mengolah dan menganalisis data kerjasama institusi Polinema menggunakan Python dan SQL untuk menghasilkan insight yang berguna. Membuat visualisasi data dan laporan analitik menggunakan Power BI atau Excel untuk mendukung pengambilan keputusan. Mendokumentasikan metodologi analisis dan menyusun rekomendasi berbasis temuan data.',
                'tools'          => 'MySQL/SQL Server, Python (data analysis), Power BI/Excel (reporting)',
                'skill'          => 'Manajemen data, analisis data, SQL, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW053 - Frontend Developer
            [
                'lowongan_id'    => 'LW053',
                'perusahaan_id'  => 'P015',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web sistem digitalisasi PT Rekaindo menggunakan React dengan tampilan yang intuitif dan responsif. Melakukan integrasi komponen frontend dengan REST API backend dan memastikan konsistensi desain sesuai Figma. Membuat dokumentasi komponen UI dan melakukan pengujian antarmuka di berbagai browser.',
                'tools'          => 'React (frontend), Figma (UI/UX), Git',
                'skill'          => 'Frontend, REST API, kemampuan kerja tim',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW054 - Backend Developer
            [
                'lowongan_id'    => 'LW054',
                'perusahaan_id'  => 'P015',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan API dan logika bisnis sistem digitalisasi PT Rekaindo menggunakan Laravel dengan pengelolaan database MySQL atau SQL Server. Merancang struktur database, melakukan normalisasi tabel, dan mengimplementasikan fitur CRUD sesuai kebutuhan sistem. Mendokumentasikan endpoint API dan menyusun ERD sebagai referensi teknis tim.',
                'tools'          => 'Laravel, MySQL/SQL Server, Git',
                'skill'          => 'Backend, perancangan database, normalisasi, REST API, kemampuan kerja tim',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW055 - UI/UX Designer
            [
                'lowongan_id'    => 'LW055',
                'perusahaan_id'  => 'P015',
                'posisi'         => 'UI/UX Designer',
                'deskripsi'      => 'Merancang antarmuka pengguna sistem digitalisasi PT Rekaindo menggunakan Figma, mulai dari wireframe hingga prototipe interaktif. Melakukan riset kebutuhan pengguna, menyusun user flow, dan memastikan desain memenuhi standar usability. Mendokumentasikan design system dan panduan gaya visual untuk diimplementasikan oleh tim frontend.',
                'tools'          => 'Figma (UI/UX), Git',
                'skill'          => 'UI-UX, kemampuan kerja tim',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW056 - IT Staff
            [
                'lowongan_id'    => 'LW056',
                'perusahaan_id'  => 'P016',
                'posisi'         => 'IT Staff',
                'deskripsi'      => 'Mendukung operasional IT harian PT JST Indonesia, termasuk pemeliharaan sistem, penanganan helpdesk, dan monitoring infrastruktur. Terlibat dalam proyek digitalisasi proses bisnis manufaktur dan membantu pengelolaan database serta laporan sistem. Mendokumentasikan prosedur operasional dan menyusun laporan aktivitas IT secara berkala.',
                'tools'          => 'Python, SQL, Power BI / Looker Studio, REST API',
                'skill'          => 'Pemrograman, analisis data, dasar AI/ML, problem solving, komunikasi dalam tim',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW057 - AI & Digitalization Intern
            [
                'lowongan_id'    => 'LW057',
                'perusahaan_id'  => 'P016',
                'posisi'         => 'AI & Digitalization Intern',
                'deskripsi'      => 'Terlibat dalam pengembangan dan implementasi solusi AI atau machine learning untuk mendukung otomasi proses manufaktur PT JST Indonesia. Membangun dashboard monitoring menggunakan Python dan Power BI, serta mengintegrasikan hasil model ke dalam sistem yang berjalan. Mendokumentasikan eksperimen AI dan menyusun laporan hasil implementasi digitalisasi.',
                'tools'          => 'Python, SQL, Power BI / Looker Studio, tools AI/ML (sesuai proyek), REST API',
                'skill'          => 'Pemrograman, analisis data, dasar AI/ML, problem solving, komunikasi dalam tim',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW058 - Magang Teknologi Informasi
            [
                'lowongan_id'    => 'LW058',
                'perusahaan_id'  => 'P017',
                'posisi'         => 'Magang Teknologi Informasi',
                'deskripsi'      => 'Mendukung kegiatan operasional dan teknis di divisi TI PT Green Energi Utama sesuai kompetensi akademik yang dimiliki. Terlibat dalam pengelolaan sistem informasi, pemeliharaan infrastruktur teknologi, dan pengembangan solusi digital internal. Menyusun laporan kegiatan harian dan mendokumentasikan proses teknis yang dikerjakan selama magang.',
                'tools'          => 'Microsoft Office, tools sesuai bidang penempatan',
                'skill'          => 'Kompetensi sesuai jurusan (IT/Engineering), komunikasi, disiplin, kerja tim',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW059 - Engineering (sesuai jurusan)
            [
                'lowongan_id'    => 'LW059',
                'perusahaan_id'  => 'P017',
                'posisi'         => 'Engineering (sesuai jurusan)',
                'deskripsi'      => 'Mendukung kegiatan teknis di bidang engineering PT Green Energi Utama sesuai jurusan dan kompetensi yang dimiliki. Berpartisipasi aktif dalam proyek lapangan atau pengembangan sistem operasional perusahaan energi terbarukan. Menyusun laporan teknis dan mendokumentasikan hasil pekerjaan selama periode magang.',
                'tools'          => 'Microsoft Office, tools sesuai bidang penempatan',
                'skill'          => 'Kompetensi sesuai jurusan (IT/Engineering), komunikasi, disiplin, kerja tim',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW060 - Web Developer
            [
                'lowongan_id'    => 'LW060',
                'perusahaan_id'  => 'P018',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Mengembangkan dan memperbarui website UPA Bahasa Polinema menggunakan PHP atau Laravel, termasuk fitur kursus dan pembelajaran mandiri TOEIC/TOEFL/IELTS. Melakukan perbaikan bug, optimasi performa halaman, dan integrasi layanan terjemahan ke dalam sistem. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk pengelola website.',
                'tools'          => 'PHP/Laravel atau WordPress (web), MySQL',
                'skill'          => 'Web development, komunikasi',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW061 - Content Creator
            [
                'lowongan_id'    => 'LW061',
                'perusahaan_id'  => 'P018',
                'posisi'         => 'Content Creator',
                'deskripsi'      => 'Membuat konten digital untuk website dan Instagram UPA Bahasa Polinema, termasuk copywriting, desain visual menggunakan Canva atau Figma, dan jadwal posting. Mengelola konsistensi identitas visual brand UPA Bahasa di berbagai platform digital. Menyusun laporan performa konten dan memberikan rekomendasi strategi konten berdasarkan data engagement.',
                'tools'          => 'Canva/Figma (konten visual), Instagram tools',
                'skill'          => 'Pembuatan konten digital, desain grafis/visual, SEO dasar, komunikasi',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW062 - Backend/Fullstack Developer
            [
                'lowongan_id'    => 'LW062',
                'perusahaan_id'  => 'P019',
                'posisi'         => 'Backend/Fullstack Developer – Sistem Internal',
                'deskripsi'      => 'Mengembangkan fitur backend dan frontend Sistem Internal PT Peruri Wira Timur menggunakan Laravel dan JavaScript dengan fokus pada efisiensi proses bisnis. Membangun REST API, mengelola database MySQL atau SQL Server, dan mengintegrasikan layanan antar modul sistem. Mendokumentasikan arsitektur sistem, membuat ERD, dan menyusun catatan teknis pengembangan.',
                'tools'          => 'Laravel (PHP), MySQL, SQL Server, JavaScript, Node.js, Git & GitHub, Postman',
                'skill'          => 'Laravel, MySQL, REST API, JavaScript, Git, SQL Server (bonus), Node.js, System Design, ERD',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW063 - SOC Analyst
            [
                'lowongan_id'    => 'LW063',
                'perusahaan_id'  => 'P020',
                'posisi'         => 'SOC Analyst',
                'deskripsi'      => 'Melakukan monitoring ancaman siber dan analisis insiden keamanan menggunakan tools SIEM seperti Wazuh di PT Sekuriti Siber Indonesia. Menganalisis log sistem, mendeteksi anomali trafik jaringan, dan menyusun laporan insiden keamanan secara terstruktur. Mendokumentasikan prosedur respons insiden dan memberikan rekomendasi mitigasi ancaman.',
                'tools'          => 'SIEM tools (Wazuh, Splunk/ELK), Wireshark, Nmap, log analysis tools, Microsoft Office',
                'skill'          => 'Monitoring keamanan, analisis log, pemahaman SIEM, networking',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW064 - IT Compliance
            [
                'lowongan_id'    => 'LW064',
                'perusahaan_id'  => 'P020',
                'posisi'         => 'IT Compliance',
                'deskripsi'      => 'Mendukung pengelolaan kepatuhan keamanan informasi dan dokumentasi kebijakan IT di PT Sekuriti Siber Indonesia. Melakukan audit internal, gap analysis terhadap regulasi keamanan yang berlaku, dan menyusun laporan compliance secara berkala. Mendokumentasikan prosedur kepatuhan dan membantu penyusunan kebijakan keamanan informasi perusahaan.',
                'tools'          => 'SIEM tools (Wazuh, Splunk/ELK), Wireshark, Nmap, log analysis tools, Microsoft Office',
                'skill'          => 'Pemahaman regulasi keamanan informasi, dokumentasi, analisis',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW065 - Cybersecurity & IT Governance
            [
                'lowongan_id'    => 'LW065',
                'perusahaan_id'  => 'P021',
                'posisi'         => 'Cybersecurity & IT Governance',
                'deskripsi'      => 'Menerapkan kebijakan keamanan informasi dan membantu pengelolaan risiko IT di PT PAL Indonesia sesuai standar yang berlaku. Melakukan analisis kerentanan, penyusunan dokumentasi kebijakan keamanan, dan peningkatan kesadaran keamanan bagi pengguna internal. Mendokumentasikan temuan audit dan menyusun rekomendasi peningkatan postur keamanan organisasi.',
                'tools'          => 'SIEM, Wireshark, firewall tools',
                'skill'          => 'Keamanan informasi (IT Governance)',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW066 - Infrastruktur TI
            [
                'lowongan_id'    => 'LW066',
                'perusahaan_id'  => 'P021',
                'posisi'         => 'Infrastruktur TI',
                'deskripsi'      => 'Mengelola dan memantau jaringan serta server infrastruktur TI PT PAL Indonesia, termasuk troubleshooting dan pemeliharaan rutin. Melakukan konfigurasi perangkat jaringan Cisco atau Mikrotik, monitoring performa sistem, dan penanganan gangguan teknis. Mendokumentasikan topologi jaringan, konfigurasi perangkat, dan prosedur penanganan insiden.',
                'tools'          => 'Cisco/Mikrotik, Linux server',
                'skill'          => 'Jaringan & server (Infrastruktur TI)',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW067 - Pengembangan Aplikasi
            [
                'lowongan_id'    => 'LW067',
                'perusahaan_id'  => 'P021',
                'posisi'         => 'Pengembangan Aplikasi',
                'deskripsi'      => 'Menganalisis kebutuhan, merancang, mengimplementasikan, dan menguji aplikasi internal PT PAL Indonesia menggunakan Laravel dan MySQL. Menyusun dokumentasi teknis pengembangan aplikasi, membuat diagram alur sistem, dan berkoordinasi dengan pengguna untuk validasi fitur. Melakukan pengujian fungsional dan menyusun laporan testing sebelum aplikasi dirilis.',
                'tools'          => 'Laravel/PHP, MySQL, Git',
                'skill'          => 'Pemrograman, pengujian aplikasi (App Dev)',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW068 - Software Developer
            [
                'lowongan_id'    => 'LW068',
                'perusahaan_id'  => 'P022',
                'posisi'         => 'Software Developer',
                'deskripsi'      => 'Mengembangkan sistem informasi internal PT INKA menggunakan Laravel, termasuk implementasi fitur, pengelolaan database, dan integrasi antar modul. Melakukan analisis kebutuhan bersama pengguna internal, merancang solusi teknis, dan mendokumentasikan hasil pengembangan. Menyusun panduan teknis dan laporan progres pengembangan secara berkala.',
                'tools'          => 'Laravel (PHP)',
                'skill'          => 'Laravel, analisis data',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW069 - Data Analyst
            [
                'lowongan_id'    => 'LW069',
                'perusahaan_id'  => 'P022',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Mengolah dan menganalisis data operasional PT INKA menggunakan Looker Studio dan Excel untuk menghasilkan laporan insight yang relevan. Membuat dashboard visualisasi data, mengidentifikasi tren produksi, dan menyusun rekomendasi berbasis data untuk manajemen. Mendokumentasikan metodologi analisis dan memelihara template laporan standar perusahaan.',
                'tools'          => 'Looker Studio, Microsoft Excel, Python',
                'skill'          => 'Looker Studio, Excel, Python, analisis data',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW070 - IoT & AI Engineer
            [
                'lowongan_id'    => 'LW070',
                'perusahaan_id'  => 'P022',
                'posisi'         => 'IoT & AI Engineer',
                'deskripsi'      => 'Mengaplikasikan teknologi IoT dan Digital Twin untuk pengembangan asset tracker dan simulasi layout penempatan mesin di PT INKA. Mengembangkan pipeline AI menggunakan Python untuk analisis data sensor dan prediksi kebutuhan pemeliharaan. Mendokumentasikan arsitektur sistem IoT dan menyusun laporan hasil implementasi digital twin.',
                'tools'          => 'Python, IoT platform, AI/ML framework, tools Digital Twin',
                'skill'          => 'IoT, Digital Twin, AI/ML, Python, analisis data',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW071 - IT Intern – Software
            [
                'lowongan_id'    => 'LW071',
                'perusahaan_id'  => 'P023',
                'posisi'         => 'IT Intern – Software',
                'deskripsi'      => 'Mengembangkan dan memelihara perangkat lunak sistem informasi internal Atria Hotel Malang menggunakan teknologi web modern. Melakukan analisis kebutuhan pengguna hotel, implementasi fitur baru, dan pengelolaan database sistem hotel berbasis MySQL atau SQL Server. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk staf IT hotel.',
                'tools'          => 'Software hotel (PMS), MySQL/SQL Server',
                'skill'          => 'Software development/maintenance, pemecahan masalah teknis IT',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW072 - Network
            [
                'lowongan_id'    => 'LW072',
                'perusahaan_id'  => 'P023',
                'posisi'         => 'Network',
                'deskripsi'      => 'Mengelola dan memantau infrastruktur jaringan Atria Hotel Malang, termasuk konfigurasi perangkat Cisco dan troubleshooting koneksi. Melakukan pemeliharaan rutin jaringan, monitoring trafik, dan memastikan ketersediaan layanan internet di seluruh area hotel. Mendokumentasikan topologi jaringan dan prosedur penanganan gangguan konektivitas.',
                'tools'          => 'tools jaringan (Cisco)',
                'skill'          => 'Networking, pemecahan masalah teknis IT',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW073 - Data Analyst
            [
                'lowongan_id'    => 'LW073',
                'perusahaan_id'  => 'P023',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Mengolah data operasional hotel menggunakan Python dan Excel untuk menghasilkan laporan analitik pendukung keputusan manajemen Atria. Membuat dashboard visualisasi data occupancy, revenue, dan kepuasan tamu secara berkala. Mendokumentasikan metodologi analisis dan menyusun template laporan untuk keperluan evaluasi performa hotel.',
                'tools'          => 'Python/Excel (data analysis)',
                'skill'          => 'Analisis data, pemecahan masalah teknis IT',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW074 - Frontend Developer
            [
                'lowongan_id'    => 'LW074',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web aplikasi produk PT Intelix Global Crossing menggunakan React atau JavaScript yang responsif dan interaktif. Melakukan integrasi dengan REST API backend, implementasi fitur sesuai spesifikasi, dan pengujian tampilan di berbagai browser. Membuat dokumentasi komponen frontend dan berpartisipasi dalam code review bersama tim.',
                'tools'          => 'JavaScript/React (frontend), Git',
                'skill'          => 'Web development (frontend), komunikasi tim',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW075 - Backend Developer
            [
                'lowongan_id'    => 'LW075',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan backend dan REST API menggunakan PHP atau Laravel untuk mendukung produk digital PT Intelix Global Crossing. Merancang struktur database, mengimplementasikan logika bisnis, dan memastikan keamanan serta performa API. Mendokumentasikan endpoint API menggunakan Postman dan menyusun ERD sebagai referensi pengembangan.',
                'tools'          => 'PHP/Laravel atau Node.js (backend), MySQL/PostgreSQL, Git, Postman',
                'skill'          => 'Web development (backend), komunikasi tim',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW076 - QA Tester
            [
                'lowongan_id'    => 'LW076',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'QA Tester',
                'deskripsi'      => 'Menyusun dan mengeksekusi test case untuk pengujian fungsional produk PT Intelix Global Crossing secara menyeluruh. Mendokumentasikan temuan bug dengan detail langkah reproduksi dan berkomunikasi dengan developer untuk proses perbaikan. Membuat laporan hasil QA dan memverifikasi perbaikan sebelum produk dirilis ke tahap berikutnya.',
                'tools'          => 'Postman, Git',
                'skill'          => 'Software testing, komunikasi tim',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW077 - System Analyst
            [
                'lowongan_id'    => 'LW077',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis kebutuhan sistem bersama klien dan tim developer PT Intelix Global Crossing untuk menghasilkan spesifikasi teknis yang akurat. Menyusun dokumen BRD, SRS, dan diagram UML sebagai acuan pengembangan, serta melakukan gap analysis terhadap sistem yang berjalan. Berkoordinasi dengan stakeholder untuk validasi spesifikasi dan memastikan kelengkapan dokumentasi proyek.',
                'tools'          => 'JavaScript/React (frontend), PHP/Laravel atau Node.js (backend), MySQL/PostgreSQL, Git, Postman',
                'skill'          => 'Web development (frontend & backend), software testing, analisis sistem, komunikasi tim',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW078 - Fullstack Programmer
            [
                'lowongan_id'    => 'LW078',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Fullstack Programmer',
                'deskripsi'      => 'Mengembangkan aplikasi web end-to-end menggunakan PHP, Ruby, atau React.js di PT Dutakom Wibawa Putra termasuk R&D OLT Management Dashboard. Melakukan implementasi UI/UX, integrasi API REST atau GraphQL, dan pengujian menyeluruh dari sisi frontend maupun backend. Menyusun dokumentasi teknis fullstack dan melaporkan progres pengembangan secara rutin.',
                'tools'          => 'PHP, Ruby, React.js, MySQL, PostgreSQL, REST API, GraphQL, Git',
                'skill'          => 'PHP/Ruby/React, REST/GraphQL, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW079 - Backend Programmer
            [
                'lowongan_id'    => 'LW079',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Backend Programmer',
                'deskripsi'      => 'Membangun prototipe endpoint REST atau GraphQL menggunakan PHP atau Ruby untuk sistem internal PT Dutakom Wibawa Putra. Merancang struktur database PostgreSQL atau MySQL, mengimplementasikan logika bisnis, dan mendokumentasikan endpoint API. Melakukan pengujian performa API dan menyusun catatan teknis untuk setiap iterasi pengembangan.',
                'tools'          => 'PHP, Ruby, MySQL, PostgreSQL, REST API, GraphQL, Git',
                'skill'          => 'PHP, Ruby, REST/GraphQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW080 - Frontend Programmer
            [
                'lowongan_id'    => 'LW080',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Frontend Programmer',
                'deskripsi'      => 'Mengembangkan prototipe antarmuka pengguna menggunakan React.js untuk sistem OLT Management Dashboard PT Dutakom. Melakukan integrasi dengan API backend, mengimplementasikan komponen UI yang modular, dan memastikan responsivitas tampilan. Membuat dokumentasi komponen React dan menyusun panduan penggunaan dashboard bagi tim internal.',
                'tools'          => 'React.js, Git',
                'skill'          => 'React.js',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW081 - System Analyst
            [
                'lowongan_id'    => 'LW081',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis requirement dan menyusun dokumen BRD atau FSD untuk proyek pengembangan sistem di PT Dutakom Wibawa Putra. Membuat diagram UML, mendokumentasikan alur bisnis, dan berkoordinasi dengan tim teknis untuk memastikan spesifikasi dapat diimplementasikan. Melakukan gap analysis dan menyusun rekomendasi peningkatan sistem yang berjalan.',
                'tools'          => 'PHP, Ruby, React.js, MySQL, PostgreSQL, REST API, GraphQL, Git',
                'skill'          => 'PHP/Ruby/React, dokumentasi',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW082 - IT Infra Engineer
            [
                'lowongan_id'    => 'LW082',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'IT Infra Engineer',
                'deskripsi'      => 'Mendukung kegiatan helpdesk harian, pemeliharaan workstation, jaringan, dan sistem surveilance di PT Dutakom Wibawa Putra. Membantu implementasi kebijakan keamanan sesuai standar ISO 27001 dan manajemen mutu perusahaan. Mendokumentasikan prosedur operasional infrastruktur dan menyusun laporan insiden teknis secara berkala.',
                'tools'          => 'Cisco/networking tools',
                'skill'          => 'Networking, OS, security, ISO',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW083 - Data Center Engineer
            [
                'lowongan_id'    => 'LW083',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Data Center Engineer',
                'deskripsi'      => 'Melakukan manajemen kabel, interkoneksi perangkat, dan instalasi rack di data center PT Dutakom Wibawa Putra. Mendukung kegiatan commissioning perangkat jaringan, pemeliharaan fisik infrastruktur, dan dokumentasi inventaris data center. Menyusun laporan kondisi infrastruktur dan membantu proses pengadaan perangkat sesuai kebutuhan operasional.',
                'tools'          => 'Cisco/networking tools',
                'skill'          => 'Hardware, cabling',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW084 - Web Developer
            [
                'lowongan_id'    => 'LW084',
                'perusahaan_id'  => 'P026',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Mengembangkan dan memelihara aplikasi web klien CV Harsyad Teknologi dari tahap analisa kebutuhan hingga deployment menggunakan PHP atau Laravel. Melakukan integrasi fitur, pengelolaan database MySQL, dan pengujian fungsional aplikasi sebelum rilis. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk tim dan klien.',
                'tools'          => 'PHP/Laravel, JavaScript/React, MySQL, Git, Postman, Figma',
                'skill'          => 'Web development (frontend & backend), analisis kebutuhan, database, REST API, testing',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW085 - Software Engineer
            [
                'lowongan_id'    => 'LW085',
                'perusahaan_id'  => 'P026',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Terlibat dalam seluruh siklus pengembangan perangkat lunak di CV Harsyad Teknologi, mulai dari perancangan arsitektur hingga release aplikasi. Melakukan analisis kebutuhan, implementasi fitur backend dan frontend, serta pengujian sistem secara menyeluruh. Menyusun dokumentasi teknis, test report, dan changelog untuk setiap versi yang dirilis.',
                'tools'          => 'PHP/Laravel, JavaScript/React, MySQL, Git, Postman, Figma',
                'skill'          => 'Web development (frontend & backend), analisis kebutuhan, database, REST API, testing',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW086 - Backend Programmer
            [
                'lowongan_id'    => 'LW086',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'Backend Programmer',
                'deskripsi'      => 'Membangun layanan API dan logika bisnis aplikasi web klien DOT Indonesia menggunakan Laravel atau Node.js. Merancang dan mengimplementasikan struktur database, memastikan keamanan endpoint, dan mengoptimalkan performa query. Mendokumentasikan API menggunakan Postman dan menyusun catatan teknis perubahan backend.',
                'tools'          => 'Laravel/Node.js (backend), MySQL/PostgreSQL',
                'skill'          => 'REST API, database',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW087 - Frontend Programmer
            [
                'lowongan_id'    => 'LW087',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'Frontend Programmer',
                'deskripsi'      => 'Mengembangkan antarmuka web interaktif menggunakan React atau Vue.js untuk proyek klien DOT Indonesia yang responsif dan accessible. Melakukan integrasi komponen frontend dengan REST API, mengimplementasikan state management, dan mengoptimalkan performa rendering. Membuat dokumentasi komponen dan melakukan code review bersama tim frontend.',
                'tools'          => 'React/Vue (frontend)',
                'skill'          => 'JavaScript, framework modern',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW088 - Fullstack Programmer
            [
                'lowongan_id'    => 'LW088',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'Fullstack Programmer',
                'deskripsi'      => 'Mengembangkan aplikasi web fullstack end-to-end di DOT Indonesia menggunakan React atau Vue untuk frontend dan Laravel atau Node.js untuk backend. Merancang arsitektur sistem, melakukan integrasi layanan, dan memastikan kualitas kode melalui pengujian yang menyeluruh. Menyusun dokumentasi teknis lengkap dan berpartisipasi aktif dalam sprint planning tim.',
                'tools'          => 'Laravel/Node.js (backend), React/Vue (frontend), MySQL/PostgreSQL',
                'skill'          => 'REST API, database, JavaScript, framework modern',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW089 - AI Engineer
            [
                'lowongan_id'    => 'LW089',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Mengembangkan model dan pipeline AI atau ML untuk kebutuhan klien DOT Indonesia menggunakan Python dan TensorFlow atau PyTorch. Melakukan preprocessing data, eksperimen model, evaluasi performa, dan integrasi hasil model ke dalam aplikasi. Mendokumentasikan eksperimen, parameter model, dan menyusun laporan rekomendasi pengembangan AI.',
                'tools'          => 'Python/TensorFlow (AI)',
                'skill'          => 'Python, ML',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW090 - System Analyst
            [
                'lowongan_id'    => 'LW090',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis kebutuhan sistem, menyusun dokumen SRS dan BRD, serta membuat diagram UML untuk proyek klien DOT Indonesia. Melakukan gap analysis, berkoordinasi dengan developer dan klien untuk validasi spesifikasi, dan memastikan dokumentasi teknis lengkap dan akurat. Memantau kesesuaian implementasi dengan spesifikasi yang telah disepakati.',
                'tools'          => 'Laravel/Node.js (backend), React/Vue (frontend), MySQL/PostgreSQL',
                'skill'          => 'Analisis sistem',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW091 - UI/UX Engineer
            [
                'lowongan_id'    => 'LW091',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'UI/UX Engineer',
                'deskripsi'      => 'Merancang antarmuka pengguna aplikasi klien DOT Indonesia menggunakan Figma, dari wireframe hingga prototipe interaktif siap handoff. Melakukan riset pengguna, menyusun user flow, design system, dan memastikan konsistensi visual antar halaman. Mendokumentasikan panduan desain dan berkolaborasi dengan tim frontend dalam proses implementasi.',
                'tools'          => 'Figma',
                'skill'          => 'Figma, desain',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW092 - Data Analyst
            [
                'lowongan_id'    => 'LW092',
                'perusahaan_id'  => 'P028',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Melakukan analisis data untuk mendukung pengambilan keputusan bisnis Oyitok Group menggunakan SQL dan Python. Membuat dashboard visualisasi menggunakan Power BI atau Looker Studio dan menyusun laporan insight secara berkala. Mendokumentasikan metodologi analisis dan memberikan rekomendasi berbasis data kepada manajemen.',
                'tools'          => 'Excel, Power BI / Looker Studio, SQL (MySQL), Python (dasar), Google Sheets',
                'skill'          => 'Analisis data, administrasi sistem, visualisasi data, SQL, komunikasi',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW093 - System Administration
            [
                'lowongan_id'    => 'LW093',
                'perusahaan_id'  => 'P028',
                'posisi'         => 'System Administration',
                'deskripsi'      => 'Mengelola dan memelihara sistem administrasi digital Oyitok Group, termasuk pengelolaan database, konfigurasi sistem, dan penanganan akses pengguna. Melakukan pemeliharaan rutin infrastruktur IT, monitoring performa sistem, dan memastikan ketersediaan layanan berjalan optimal. Mendokumentasikan prosedur administrasi sistem dan menyusun laporan status infrastruktur.',
                'tools'          => 'Excel, SQL (MySQL), Google Sheets',
                'skill'          => 'Administrasi sistem, SQL, komunikasi',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW094 - Backend/Frontend Developer
            [
                'lowongan_id'    => 'LW094',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'Backend/Frontend Developer',
                'deskripsi'      => 'Mengembangkan fitur backend dan frontend aplikasi web CV DB KLIK menggunakan React.js, Node.js, atau Laravel sesuai kebutuhan proyek. Melakukan integrasi API, pengelolaan database MySQL, debugging, dan unit testing untuk memastikan kualitas kode. Mendokumentasikan perubahan fitur dan berpartisipasi dalam sprint review bersama tim.',
                'tools'          => 'React.js / Node.js / Laravel, SQL (MySQL), Git',
                'skill'          => 'RESTful API, Git, logika pemrograman',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW095 - UI/UX Designer
            [
                'lowongan_id'    => 'LW095',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'UI/UX Designer',
                'deskripsi'      => 'Merancang wireframe, user flow, dan prototipe interaktif untuk produk digital CV DB KLIK menggunakan Figma atau Adobe XD. Melakukan riset kebutuhan pengguna, menyusun design system, dan memastikan konsistensi tampilan antar halaman aplikasi. Mendokumentasikan panduan desain dan berkolaborasi dengan tim developer dalam proses implementasi.',
                'tools'          => 'Figma / Adobe XD',
                'skill'          => 'Figma/Adobe XD, portofolio desain',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW096 - System Analyst
            [
                'lowongan_id'    => 'LW096',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Menganalisis kebutuhan sistem, menyusun dokumen UML, BRD atau FRD, dan melakukan gap analysis untuk proyek CV DB KLIK. Berkoordinasi dengan tim teknis dan klien untuk memvalidasi spesifikasi sistem dan memastikan kelengkapan dokumentasi teknis. Melakukan quality assurance terhadap kesesuaian implementasi dengan spesifikasi yang telah disepakati.',
                'tools'          => 'React.js / Node.js / Laravel, SQL (MySQL), Git',
                'skill'          => 'UML, dokumentasi teknis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW097 - Data Analyst
            [
                'lowongan_id'    => 'LW097',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Melakukan pembersihan, pengolahan, dan visualisasi data operasional CV DB KLIK menggunakan SQL, Python, Tableau, atau Power BI. Menganalisis tren data, menyusun dashboard laporan, dan memberikan rekomendasi insight kepada manajemen secara berkala. Mendokumentasikan proses analisis dan memelihara template laporan standar untuk keperluan reporting.',
                'tools'          => 'Tableau / Power BI / Looker Studio, SQL (MySQL), Python',
                'skill'          => 'SQL, Python, visualisasi',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            // LW098 - Website Developer
            [
                'lowongan_id'    => 'LW098',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'Website Developer',
                'deskripsi'      => 'Mengembangkan dan memelihara website klien CV DB KLIK menggunakan React.js, Node.js, atau Laravel dengan fokus pada performa dan kemudahan penggunaan. Melakukan implementasi fitur, integrasi REST API, dan pengujian lintas browser untuk memastikan kualitas website. Mendokumentasikan perubahan kode dan menyusun panduan teknis untuk pengelola website.',
                'tools'          => 'React.js / Node.js / Laravel, SQL (MySQL), Git',
                'skill'          => 'RESTful API, Git, logika pemrograman',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        DB::table('lowongan_models')->insert($lowongan);
    }
}