<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LowonganModelSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $lowongan = [
            [
                'lowongan_id'    => 'LW001',
                'perusahaan_id'  => 'P001',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Membantu pengembangan dan pemeliharaan sistem informasi internal perusahaan menggunakan VB.NET dan MySQL. Terlibat dalam analisis kebutuhan, implementasi fitur baru, serta perbaikan bug pada sistem yang berjalan. Membuat dokumentasi teknis dan laporan pengembangan sistem secara berkala.',
                'tools'          => 'VB.NET, MySQL',
                'skill'          => 'Programming, Database Management, System Analysis, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW002',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan dan memelihara layanan REST API menggunakan Laravel atau FastAPI sebagai fondasi sistem SIPP lingkungan hidup. Melakukan integrasi data antar modul sistem, pengelolaan database MySQL/PostgreSQL, serta konfigurasi API gateway dan koneksi ke layanan cloud. Mendokumentasikan endpoint API menggunakan Postman dan menyusun catatan perubahan teknis.',
                'tools'          => 'Laravel, FastAPI, MySQL, PostgreSQL, Docker, Postman',
                'skill'          => 'REST API, Database Management, PHP, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW003',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka dashboard sistem SIPP yang responsif dan mudah digunakan menggunakan React atau Vue.js. Melakukan integrasi frontend dengan REST API backend dan menerapkan visualisasi data lingkungan hidup secara interaktif. Memastikan konsistensi tampilan dan pengalaman pengguna sesuai desain yang telah ditetapkan.',
                'tools'          => 'React.js, Vue.js',
                'skill'          => 'Web Development, HTML, CSS, JavaScript, UI/UX Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW004',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Membangun pipeline pemrosesan data untuk kebutuhan AI/LLM seperti DeepSeek, Qwen, dan Llama dalam sistem SIPP. Melakukan preprocessing data lingkungan, eksplorasi model, dan integrasi hasil prediksi ke dalam sistem. Mendokumentasikan eksperimen model dan menyusun laporan performa pipeline AI.',
                'tools'          => 'TensorFlow, PyTorch',
                'skill'          => 'Machine Learning, Data Mining, Python',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW005',
                'perusahaan_id'  => 'P002',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis kebutuhan sistem bersama stakeholder dan menyusun dokumen SRS (Software Requirements Specification) secara terstruktur. Membuat diagram alur sistem, use case diagram, dan spesifikasi fungsional menggunakan tools seperti draw.io. Melaksanakan pengujian fungsional sistem dan mendokumentasikan hasil testing serta rekomendasi perbaikan.',
                'tools'          => 'draw.io, Postman',
                'skill'          => 'System Analysis, Software Testing, System Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW006',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Membangun pipeline ETL untuk mengolah data spasial dan non-spasial dalam format CSV, SHP, dan GeoJSON ke dalam database PostGIS. Melakukan integrasi dataset dari berbagai sumber dan memastikan kualitas serta konsistensi data geospasial yang tersimpan. Mendokumentasikan proses pipeline data dan membuat laporan validasi dataset secara rutin.',
                'tools'          => 'PostGIS, FastAPI, AWS, Docker',
                'skill'          => 'Data Warehouse, Database Management, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW007',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan endpoint API menggunakan Python FastAPI untuk mendukung platform WebGIS Satu Peta Jawa Timur. Melakukan integrasi layanan GIS, implementasi logika bisnis pada sisi server, serta pengelolaan query data spasial di PostGIS. Menyusun dokumentasi API dan memastikan performa endpoint sesuai standar yang ditetapkan.',
                'tools'          => 'PostGIS, FastAPI, AWS, Docker',
                'skill'          => 'Web Development, REST API, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW008',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun dashboard peta interaktif menggunakan OpenLayers atau Leaflet.js untuk visualisasi data geospasial Jawa Timur. Mengintegrasikan komponen WebGIS dengan REST API backend dan memastikan tampilan responsif di berbagai perangkat. Membuat dokumentasi komponen frontend dan panduan penggunaan fitur peta.',
                'tools'          => 'OpenLayers, Leaflet',
                'skill'          => 'Web Development, JavaScript, WebGIS',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW009',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Mengeksplorasi dan mengembangkan model AI/LLM untuk kebutuhan metadata otomatis dan prediksi data geospasial. Membangun pipeline pemrosesan data menggunakan Python dan mengintegrasikan hasil model ke dalam sistem Platform Satu Peta. Mendokumentasikan eksperimen, hasil evaluasi model, dan rekomendasi pengembangan lanjutan.',
                'tools'          => 'PostGIS, FastAPI, AWS, Docker',
                'skill'          => 'Data Mining, Machine Learning, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW010',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola proses deployment aplikasi WebGIS ke lingkungan cloud AWS menggunakan Docker dan CI/CD pipeline. Melakukan containerization layanan, konfigurasi monitoring sistem, serta memastikan ketersediaan dan performa infrastruktur. Menyusun dokumentasi deployment dan runbook penanganan insiden.',
                'tools'          => 'AWS, Docker, CI/CD',
                'skill'          => 'Operating System, Linux',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW011',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Blockchain Engineer',
                'deskripsi'      => 'Mengembangkan smart contract menggunakan Hyperledger Fabric dan melakukan integrasi middleware blockchain ke dalam sistem backend. Membangun dan menguji chaincode, serta mendokumentasikan arsitektur jaringan blockchain dan alur transaksi. Berkolaborasi dengan tim backend untuk memastikan integrasi berjalan sesuai spesifikasi.',
                'tools'          => 'Hyperledger Fabric, Node.js, Docker, AWS',
                'skill'          => 'Programming, Python, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW012',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan REST API dan microservices menggunakan Python atau Node.js untuk mendukung sistem berbasis blockchain di PT ARM Solusi. Merancang dan mengimplementasikan data pipeline, mengelola database SQL, serta mendokumentasikan arsitektur layanan backend. Berkolaborasi dengan tim DevOps untuk deployment menggunakan Docker dan AWS.',
                'tools'          => 'Node.js, MySQL, PostgreSQL, Docker, AWS',
                'skill'          => 'Web Development, REST API, Python, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW013',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Melakukan preprocessing dan analisis log transaksi blockchain untuk kebutuhan audit data dan pelaporan. Membangun pipeline data menggunakan Python, melakukan validasi integritas data, dan menyajikan hasil analisis dalam bentuk laporan visual. Mendokumentasikan proses ETL dan menyusun catatan temuan audit secara berkala.',
                'tools'          => 'Grafana, Prometheus',
                'skill'          => 'Data Analysis, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW014',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan dashboard visualisasi log transaksi dan verifikasi data blockchain menggunakan React. Mengintegrasikan komponen frontend dengan API backend dan menampilkan data audit secara real-time. Membuat dokumentasi komponen UI dan panduan penggunaan dashboard bagi pengguna internal.',
                'tools'          => 'React.js, Node.js',
                'skill'          => 'Web Development, JavaScript, UI/UX Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW015',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Membangun dan mengoptimalkan pipeline ML serta mengintegrasikan model LLM seperti DeepSeek dan Qwen ke dalam sistem PT ARM Solusi. Melakukan eksperimen, evaluasi performa model, dan penyesuaian prompt engineering sesuai kebutuhan bisnis. Mendokumentasikan hasil eksperimen dan menyusun laporan rekomendasi model terbaik.',
                'tools'          => 'Grafana, Prometheus',
                'skill'          => 'Machine Learning, Python',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW016',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi fullstack AI Workspace dari sisi frontend hingga backend menggunakan React dan Python. Mengintegrasikan modul AI ke dalam antarmuka pengguna dan memastikan alur data berjalan optimal antar layanan. Menyusun dokumentasi teknis end-to-end dan melakukan pengujian integrasi sistem.',
                'tools'          => 'React.js, Node.js, Docker, AWS',
                'skill'          => 'Web Development, REST API, Python, JavaScript, SQL, Machine Learning',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW017',
                'perusahaan_id'  => 'P004',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola proses deployment, containerization dengan Docker, dan konfigurasi infrastruktur cloud AWS untuk sistem PT ARM Solusi. Membangun dan memelihara pipeline CI/CD, melakukan monitoring menggunakan Grafana dan Prometheus, serta merespons insiden infrastruktur. Mendokumentasikan konfigurasi deployment dan prosedur operasional standar.',
                'tools'          => 'Docker, AWS, Grafana, Prometheus, CI/CD',
                'skill'          => 'Operating System, Linux',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW018',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Membangun pipeline ETL untuk mengolah data spasial dan non-spasial batch kedua Platform Satu Peta Jatim, termasuk harmonisasi dataset dan manajemen PostGIS. Melakukan validasi kualitas data geospasial dan memastikan konsistensi format antar dataset yang terintegrasi. Mendokumentasikan proses pipeline dan membuat laporan status data secara berkala.',
                'tools'          => 'PostGIS, FastAPI, AWS, Docker',
                'skill'          => 'Data Warehouse, Database Management, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW019',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan endpoint API menggunakan FastAPI untuk mendukung layanan batch kedua Platform Satu Peta Jatim. Melakukan integrasi layanan GIS, optimasi query PostGIS, dan pemeliharaan logika bisnis pada sisi server. Menyusun dokumentasi API dan laporan pengembangan fitur backend secara rutin.',
                'tools'          => 'PostGIS, FastAPI, AWS, Docker',
                'skill'          => 'Web Development, REST API, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW020',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun dashboard WebGIS interaktif menggunakan OpenLayers atau Leaflet.js untuk batch kedua Platform Satu Peta Jatim. Mengintegrasikan komponen peta dengan REST API dan memastikan performa rendering data geospasial secara real-time. Membuat dokumentasi komponen frontend dan panduan teknis pengembangan peta.',
                'tools'          => 'OpenLayers, Leaflet',
                'skill'          => 'Web Development, JavaScript, WebGIS',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW021',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Mengeksplorasi model AI untuk prediksi geospasial dan membangun pipeline pemrosesan data batch kedua Platform Satu Peta Jatim. Melakukan evaluasi model, integrasi hasil prediksi ke dalam sistem, dan mendokumentasikan eksperimen secara terstruktur. Berkolaborasi dengan tim data untuk memastikan kualitas input dan output model.',
                'tools'          => 'PostGIS, FastAPI, AWS, Docker',
                'skill'          => 'Data Mining, Machine Learning, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW022',
                'perusahaan_id'  => 'P003',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola deployment batch kedua Platform Satu Peta Jatim pada infrastruktur hybrid cloud AWS dan on-premise. Mengkonfigurasi containerization, pipeline CI/CD, monitoring sistem, serta memastikan ketersediaan layanan secara konsisten. Menyusun dokumentasi arsitektur infrastruktur dan runbook operasional.',
                'tools'          => 'AWS, Docker, CI/CD',
                'skill'          => 'Operating System, Linux',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW023',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Mengembangkan fitur backend sistem ERP-BPM Sarastya menggunakan Laravel atau Node.js, termasuk implementasi REST API dan pengelolaan database. Melakukan integrasi antar modul sistem dan memastikan performa layanan backend sesuai kebutuhan klien. Mendokumentasikan endpoint API dan menyusun catatan perubahan teknis secara berkala.',
                'tools'          => 'Laravel, Node.js, MySQL, PostgreSQL',
                'skill'          => 'Web Development, REST API, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW024',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun antarmuka web dan mobile sistem ERP-BPM menggunakan React atau framework modern yang responsif. Melakukan integrasi frontend dengan REST API backend dan memastikan pengalaman pengguna yang konsisten di berbagai perangkat. Membuat dokumentasi komponen UI dan panduan penggunaan fitur bagi end user.',
                'tools'          => 'React.js',
                'skill'          => 'Web Development, Mobile Development, JavaScript',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW025',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi web dan mobile end-to-end pada sistem ERP-BPM Sarastya dari sisi frontend maupun backend. Melakukan integrasi modul, pengelolaan state aplikasi, dan pemeliharaan API yang sudah berjalan. Menyusun dokumentasi teknis fullstack dan melakukan pengujian integrasi secara menyeluruh.',
                'tools'          => 'Laravel, Node.js, React.js',
                'skill'          => 'Web Development, Mobile Development, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW026',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola deployment dan pemeliharaan server sistem ERP-BPM Sarastya, termasuk konfigurasi environment dan monitoring performa. Melakukan troubleshooting infrastruktur, pengelolaan dependensi layanan, dan memastikan uptime sistem. Mendokumentasikan konfigurasi server dan prosedur operasional harian.',
                'tools'          => 'Cisco, Mikrotik',
                'skill'          => 'Computer Networking, Operating System, IT Governance',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW027',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Menganalisis data klien pada sistem ERP-BPM menggunakan Power BI dan Python untuk menghasilkan insight yang actionable. Membuat laporan visualisasi data, dashboard performa bisnis, dan rekomendasi berbasis data bagi manajemen klien. Mendokumentasikan metodologi analisis dan menyusun template laporan standar.',
                'tools'          => 'Power BI',
                'skill'          => 'Data Analysis, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW028',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Business Analyst',
                'deskripsi'      => 'Menganalisis data pemasaran dan penjualan klien untuk mendukung pengambilan keputusan bisnis berbasis data pada sistem ERP-BPM. Menyusun laporan analisis bisnis, melakukan identifikasi tren pasar, dan memberikan rekomendasi strategis yang terukur. Mendokumentasikan temuan analisis dan mempresentasikan hasil kepada stakeholder terkait.',
                'tools'          => 'Power BI',
                'skill'          => 'Business Analysis, Data Analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW029',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'IT Governance & Compliance',
                'deskripsi'      => 'Membantu implementasi tata kelola TI dan kebijakan e-governance pada sistem ERP-BPM di lingkungan klien Sarastya. Menyusun dokumentasi prosedur operasional, melakukan gap analysis terhadap regulasi yang berlaku, dan mendukung audit internal sistem. Berkolaborasi dengan tim teknis untuk memastikan kepatuhan sistem terhadap standar yang ditetapkan.',
                'tools'          => 'ISO 27001',
                'skill'          => 'IT Governance, Compliance, Business Analysis',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW030',
                'perusahaan_id'  => 'P005',
                'posisi'         => 'Network Engineer',
                'deskripsi'      => 'Melakukan pemeliharaan server dan memastikan keamanan jaringan pada infrastruktur klien Sarastya Agility Innovations. Mengkonfigurasi perangkat jaringan Cisco/Mikrotik, melakukan monitoring trafik, dan menangani gangguan konektivitas. Mendokumentasikan topologi jaringan dan prosedur penanganan insiden jaringan.',
                'tools'          => 'Cisco, Mikrotik, Wireshark',
                'skill'          => 'Computer Networking, Operating System',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW031',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web yang responsif dan user-friendly menggunakan React atau Next.js untuk proyek klien PT Time Door Indonesia. Melakukan implementasi desain UI/UX ke dalam komponen frontend, integrasi dengan REST API, dan optimasi performa halaman. Membuat dokumentasi komponen dan melakukan code review bersama tim.',
                'tools'          => 'React.js, Next.js',
                'skill'          => 'Web Development, HTML, CSS, JavaScript, UI/UX Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW032',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'Quality Assurance (QA)',
                'deskripsi'      => 'Melakukan pengujian fungsional dan otomatis pada aplikasi web dan mobile menggunakan Playwright atau Selenium. Menyusun test case, mendokumentasikan temuan bug, serta berkoordinasi dengan developer untuk proses perbaikan. Membuat laporan hasil testing secara berkala dan memastikan kualitas produk sebelum dirilis.',
                'tools'          => 'Playwright, Selenium',
                'skill'          => 'Software Testing, Quality Assurance',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW033',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Mengimplementasikan modul AI ke dalam sistem klien PT Time Door menggunakan Python dan framework TensorFlow atau PyTorch. Melakukan preprocessing data, pelatihan model, dan integrasi hasil prediksi ke dalam aplikasi yang berjalan. Mendokumentasikan pipeline AI dan menyusun laporan evaluasi performa model.',
                'tools'          => 'TensorFlow, PyTorch',
                'skill'          => 'Machine Learning, Data Mining, Python',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW034',
                'perusahaan_id'  => 'P006',
                'posisi'         => 'DevOps Engineer',
                'deskripsi'      => 'Mengelola proses deployment aplikasi ke cloud AWS atau GCP menggunakan Docker dan pipeline CI/CD di PT Time Door Indonesia. Mengkonfigurasi environment staging dan production, melakukan monitoring performa sistem, serta menangani insiden infrastruktur. Menyusun dokumentasi deployment dan runbook operasional tim.',
                'tools'          => 'Docker, AWS, GCP, CI/CD',
                'skill'          => 'Operating System, Linux',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW035',
                'perusahaan_id'  => 'P007',
                'posisi'         => 'Mobile Developer',
                'deskripsi'      => 'Mengembangkan fitur aplikasi mobile cross-platform menggunakan Flutter dan Dart untuk produk Maxchat. Melakukan integrasi dengan REST API backend, implementasi state management, dan pengujian UI di berbagai perangkat. Mendokumentasikan komponen Flutter dan menyusun catatan changelog untuk setiap rilis fitur.',
                'tools'          => 'Flutter, Firebase, Postman',
                'skill'          => 'Mobile Development, Dart, REST API',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW036',
                'perusahaan_id'  => 'P007',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun dan memelihara layanan API backend menggunakan Node.js atau Go untuk mendukung platform Maxchat. Melakukan pengelolaan database, implementasi logika bisnis, dan integrasi dengan layanan WhatsApp Business API. Mendokumentasikan endpoint API menggunakan Postman dan menyusun catatan teknis perubahan sistem.',
                'tools'          => 'Node.js, Go, Postman',
                'skill'          => 'Web Development, REST API, JavaScript',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW037',
                'perusahaan_id'  => 'P007',
                'posisi'         => 'Quality Assurance (QA)',
                'deskripsi'      => 'Menyusun dan mengeksekusi skenario pengujian otomatis menggunakan Playwright atau Cypress untuk aplikasi Maxchat. Mengidentifikasi dan mendokumentasikan bug, membuat laporan hasil testing, serta berkolaborasi dengan tim developer untuk verifikasi perbaikan. Memelihara dan memperbarui skrip pengujian sesuai perkembangan fitur.',
                'tools'          => 'Playwright, Cypress',
                'skill'          => 'Software Testing, Quality Assurance',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW038',
                'perusahaan_id'  => 'P008',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Mengembangkan fitur baru dan memperbaiki bug pada aplikasi berbasis Flutter atau web di Politeknik Batu. Melakukan integrasi dengan API, pengelolaan state aplikasi, dan pengujian fungsional fitur yang dikembangkan. Mendokumentasikan perubahan kode dan menyusun laporan progres pengembangan secara rutin.',
                'tools'          => 'Flutter, Laravel, MySQL, Postman',
                'skill'          => 'Programming, Web Development, Mobile Development, PHP, Dart, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW039',
                'perusahaan_id'  => 'P008',
                'posisi'         => 'Quality Assurance (QA)',
                'deskripsi'      => 'Melakukan pengujian fungsional aplikasi Flutter dan web milik Politeknik Batu secara menyeluruh berdasarkan test case yang telah disusun. Mendokumentasikan temuan bug lengkap dengan langkah reproduksi dan tingkat keparahan, serta memverifikasi hasil perbaikan dari developer. Membuat laporan QA mingguan dan menyusun rekomendasi peningkatan kualitas.',
                'tools'          => 'Postman',
                'skill'          => 'Software Testing, Quality Assurance',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW040',
                'perusahaan_id'  => 'P008',
                'posisi'         => 'Quality Assurance (QA)',
                'deskripsi'      => 'Melaksanakan pengujian manual aplikasi internal Politeknik Batu dengan menyusun skenario uji dan test case yang komprehensif. Mendokumentasikan hasil pengujian, mencatat temuan defect, dan berkoordinasi dengan tim pengembang untuk proses perbaikan. Membuat laporan testing akhir sebagai dasar keputusan rilis aplikasi.',
                'tools'          => 'Postman',
                'skill'          => 'Software Testing, Quality Assurance',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW041',
                'perusahaan_id'  => 'P009',
                'posisi'         => 'Game Developer',
                'deskripsi'      => 'Mengimplementasikan fitur gameplay dan sistem game menggunakan Unity dan C# pada proyek game Ariverse Studio. Melakukan debugging, optimasi performa, dan profiling untuk memastikan game berjalan lancar di target platform. Mendokumentasikan arsitektur sistem game dan menyusun catatan teknis untuk anggota tim.',
                'tools'          => 'Unity, C#, Git',
                'skill'          => 'Object Oriented Programming, Programming',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW042',
                'perusahaan_id'  => 'P009',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi web atau mobile fullstack menggunakan Flutter atau React untuk frontend dan Laravel atau ElysiaJS untuk backend. Merancang dan mengimplementasikan REST API, mengelola database relasional, serta melakukan pengujian integrasi. Mendokumentasikan arsitektur sistem dan menyusun panduan setup project untuk tim.',
                'tools'          => 'Flutter, React.js, Next.js, Laravel, MySQL, Git',
                'skill'          => 'Web Development, Mobile Development, PHP, JavaScript, Dart, SQL, REST API',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW043',
                'perusahaan_id'  => 'P009',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Membangun antarmuka web yang responsif menggunakan React atau Next.js sesuai desain Figma yang telah disepakati tim Ariverse Studio. Melakukan integrasi komponen frontend dengan REST API, memastikan konsistensi UI, dan mengoptimalkan performa halaman. Membuat dokumentasi komponen dan melakukan review kode bersama senior developer.',
                'tools'          => 'React.js, Next.js, Figma, Git',
                'skill'          => 'Web Development, HTML, CSS, JavaScript, UI/UX Design',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW044',
                'perusahaan_id'  => 'P010',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Menganalisis data Google Analytics, performa website, dan data media sosial Humas Polinema untuk menghasilkan insight komunikasi. Membuat visualisasi data menggunakan Looker Studio atau Tableau dan menyusun laporan insight secara berkala. Memberikan rekomendasi berbasis data untuk mendukung strategi komunikasi digital institusi.',
                'tools'          => 'Google Analytics, Looker Studio, Tableau, Pandas, Matplotlib',
                'skill'          => 'Data Analysis, SQL, Python',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW045',
                'perusahaan_id'  => 'P010',
                'posisi'         => 'Social Media Analyst',
                'deskripsi'      => 'Menganalisis data engagement, reach, dan performa konten media sosial Humas Polinema menggunakan tools social media analytics. Menyusun laporan performa akun secara mingguan dan bulanan, serta memberikan rekomendasi strategi konten berbasis data. Mendokumentasikan tren dan pola audiens untuk mendukung perencanaan konten ke depan.',
                'tools'          => 'Google Analytics, Looker Studio, Tableau, Pandas, Matplotlib',
                'skill'          => 'Data Analysis, SQL, Python',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW046',
                'perusahaan_id'  => 'P011',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi fullstack yang terintegrasi dengan n8n untuk workflow automation dan WebSocket untuk komunikasi real-time. Membangun komponen frontend menggunakan React atau Next.js serta backend dengan Node.js atau Laravel, sekaligus mengintegrasikan AI chatbot berbasis LLM. Menyusun dokumentasi teknis sistem dan membuat diagram arsitektur integrasi layanan.',
                'tools'          => 'React.js, Next.js, Node.js, Laravel, MySQL, PostgreSQL',
                'skill'          => 'Web Development, REST API, JavaScript, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW047',
                'perusahaan_id'  => 'P012',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan fitur aplikasi web menggunakan JavaScript, Node.js, dan React atau Next.js pada proyek PT Utero Kreatif Indonesia. Melakukan integrasi frontend-backend, pengelolaan database PostgreSQL, dan memastikan performa serta skalabilitas aplikasi. Mendokumentasikan kode, menyusun catatan teknis, dan berpartisipasi dalam code review bersama tim.',
                'tools'          => 'Node.js, React.js, Next.js, Express, MySQL, PostgreSQL, Git',
                'skill'          => 'Web Development, REST API, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW048',
                'perusahaan_id'  => 'P012',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Terlibat dalam analisis kebutuhan bisnis, perancangan arsitektur sistem, dan implementasi fitur berbasis web di PT Utero Kreatif Indonesia. Mengembangkan solusi teknis yang efisien dan terukur menggunakan stack JavaScript modern dengan pendekatan berbasis data. Menyusun dokumentasi teknis, ERD, dan spesifikasi sistem untuk keperluan pengembangan dan pemeliharaan.',
                'tools'          => 'Node.js, React.js, Next.js, Express, MySQL, PostgreSQL, Git',
                'skill'          => 'Software Engineering, Web Development, System Analysis, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW049',
                'perusahaan_id'  => 'P013',
                'posisi'         => 'Operasional Hotel',
                'deskripsi'      => 'Menjalankan tugas operasional harian di berbagai departemen hotel sesuai penempatan, meliputi front office, housekeeping, atau food & beverage. Memberikan pelayanan tamu sesuai standar operasional The Himana Hotel dan belajar langsung dari supervisor lapangan. Menyusun laporan kegiatan magang harian dan mengikuti briefing operasional hotel secara rutin.',
                'tools'          => 'Microsoft Excel',
                'skill'          => 'Business Analysis',
                'ipk_min'        => null,
                'periode'        => 5,
                'insentif'       => 'Flexible',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW050',
                'perusahaan_id'  => 'P014',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Memodifikasi dan mengembangkan sistem web Bidang Kerjasama Polinema menggunakan PHP atau Laravel sesuai kebutuhan pengguna. Melakukan perbaikan bug, penambahan fitur baru, dan memastikan antarmuka sistem mudah digunakan. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk administrator.',
                'tools'          => 'Laravel, MySQL, SQL Server',
                'skill'          => 'Web Development, Database Management, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW051',
                'perusahaan_id'  => 'P014',
                'posisi'         => 'Data Engineer',
                'deskripsi'      => 'Mengelola dan mengorganisir penyimpanan dokumen digital kerjasama institusi Polinema menggunakan sistem database yang terstruktur. Melakukan klasifikasi, indexing, dan pemeliharaan integritas data dokumen di MySQL atau SQL Server. Menyusun dokumentasi prosedur pengelolaan data dan membuat laporan inventaris dokumen secara berkala.',
                'tools'          => 'MySQL, SQL Server',
                'skill'          => 'Data Warehouse, Database Management, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW052',
                'perusahaan_id'  => 'P014',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Mengolah dan menganalisis data kerjasama institusi Polinema menggunakan Python dan SQL untuk menghasilkan insight yang berguna. Membuat visualisasi data dan laporan analitik menggunakan Power BI atau Excel untuk mendukung pengambilan keputusan. Mendokumentasikan metodologi analisis dan menyusun rekomendasi berbasis temuan data.',
                'tools'          => 'MySQL, SQL Server, Power BI, Microsoft Excel',
                'skill'          => 'Data Analysis, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW053',
                'perusahaan_id'  => 'P015',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web sistem digitalisasi PT Rekaindo menggunakan React dengan tampilan yang intuitif dan responsif. Melakukan integrasi komponen frontend dengan REST API backend dan memastikan konsistensi desain sesuai Figma. Membuat dokumentasi komponen UI dan melakukan pengujian antarmuka di berbagai browser.',
                'tools'          => 'React.js, Figma, Git',
                'skill'          => 'Web Development, REST API, JavaScript, UI/UX Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW054',
                'perusahaan_id'  => 'P015',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan API dan logika bisnis sistem digitalisasi PT Rekaindo menggunakan Laravel dengan pengelolaan database MySQL atau SQL Server. Merancang struktur database, melakukan normalisasi tabel, dan mengimplementasikan fitur CRUD sesuai kebutuhan sistem. Mendokumentasikan endpoint API dan menyusun ERD sebagai referensi teknis tim.',
                'tools'          => 'Laravel, MySQL, SQL Server, Git',
                'skill'          => 'Web Development, Database Management, REST API, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW055',
                'perusahaan_id'  => 'P015',
                'posisi'         => 'UI/UX Designer',
                'deskripsi'      => 'Merancang antarmuka pengguna sistem digitalisasi PT Rekaindo menggunakan Figma, mulai dari wireframe hingga prototipe interaktif. Melakukan riset kebutuhan pengguna, menyusun user flow, dan memastikan desain memenuhi standar usability. Mendokumentasikan design system dan panduan gaya visual untuk diimplementasikan oleh tim frontend.',
                'tools'          => 'Figma, Git',
                'skill'          => 'UI/UX Design, System Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW056',
                'perusahaan_id'  => 'P016',
                'posisi'         => 'IT Support Specialist',
                'deskripsi'      => 'Mendukung operasional IT harian PT JST Indonesia, termasuk pemeliharaan sistem, penanganan helpdesk, dan monitoring infrastruktur. Terlibat dalam proyek digitalisasi proses bisnis manufaktur dan membantu pengelolaan database serta laporan sistem. Mendokumentasikan prosedur operasional dan menyusun laporan aktivitas IT secara berkala.',
                'tools'          => 'Power BI, Looker Studio',
                'skill'          => 'Database Management, Data Analysis, Python, SQL, REST API',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW057',
                'perusahaan_id'  => 'P016',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Terlibat dalam pengembangan dan implementasi solusi AI atau machine learning untuk mendukung otomasi proses manufaktur PT JST Indonesia. Membangun dashboard monitoring menggunakan Python dan Power BI, serta mengintegrasikan hasil model ke dalam sistem yang berjalan. Mendokumentasikan eksperimen AI dan menyusun laporan hasil implementasi digitalisasi.',
                'tools'          => 'Power BI, Looker Studio',
                'skill'          => 'Machine Learning, Data Analysis, Python, SQL, REST API',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW058',
                'perusahaan_id'  => 'P017',
                'posisi'         => 'IT Support Specialist',
                'deskripsi'      => 'Mendukung kegiatan operasional dan teknis di divisi TI PT Green Energi Utama sesuai kompetensi akademik yang dimiliki. Terlibat dalam pengelolaan sistem informasi, pemeliharaan infrastruktur teknologi, dan pengembangan solusi digital internal. Menyusun laporan kegiatan harian dan mendokumentasikan proses teknis yang dikerjakan selama magang.',
                'tools'          => 'Microsoft Excel',
                'skill'          => 'Programming, Database Management, Computer Networking',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW059',
                'perusahaan_id'  => 'P017',
                'posisi'         => 'Engineering Staff',
                'deskripsi'      => 'Mendukung kegiatan teknis di bidang engineering PT Green Energi Utama sesuai jurusan dan kompetensi yang dimiliki. Berpartisipasi aktif dalam proyek lapangan atau pengembangan sistem operasional perusahaan energi terbarukan. Menyusun laporan teknis dan mendokumentasikan hasil pekerjaan selama periode magang.',
                'tools'          => 'Microsoft Excel',
                'skill'          => 'Project Management',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW060',
                'perusahaan_id'  => 'P018',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Mengembangkan dan memperbarui website UPA Bahasa Polinema menggunakan PHP atau Laravel, termasuk fitur kursus dan pembelajaran mandiri TOEIC/TOEFL/IELTS. Melakukan perbaikan bug, optimasi performa halaman, dan integrasi layanan terjemahan ke dalam sistem. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk pengelola website.',
                'tools'          => 'Laravel, WordPress, MySQL',
                'skill'          => 'Web Development, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW061',
                'perusahaan_id'  => 'P018',
                'posisi'         => 'Content Creator',
                'deskripsi'      => 'Membuat konten digital untuk website dan Instagram UPA Bahasa Polinema, termasuk copywriting, desain visual menggunakan Canva atau Figma, dan jadwal posting. Mengelola konsistensi identitas visual brand UPA Bahasa di berbagai platform digital. Menyusun laporan performa konten dan memberikan rekomendasi strategi konten berdasarkan data engagement.',
                'tools'          => 'Canva, Figma',
                'skill'          => 'UI/UX Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Unpaid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW062',
                'perusahaan_id'  => 'P019',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan fitur backend dan frontend Sistem Internal PT Peruri Wira Timur menggunakan Laravel dan JavaScript dengan fokus pada efisiensi proses bisnis. Membangun REST API, mengelola database MySQL atau SQL Server, dan mengintegrasikan layanan antar modul sistem. Mendokumentasikan arsitektur sistem, membuat ERD, dan menyusun catatan teknis pengembangan.',
                'tools'          => 'Laravel, MySQL, SQL Server, Node.js, Git, GitHub, Postman',
                'skill'          => 'Web Development, REST API, System Design, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW063',
                'perusahaan_id'  => 'P020',
                'posisi'         => 'Cybersecurity Analyst',
                'deskripsi'      => 'Melakukan monitoring ancaman siber dan analisis insiden keamanan menggunakan tools SIEM seperti Wazuh di PT Sekuriti Siber Indonesia. Menganalisis log sistem, mendeteksi anomali trafik jaringan, dan menyusun laporan insiden keamanan secara terstruktur. Mendokumentasikan prosedur respons insiden dan memberikan rekomendasi mitigasi ancaman.',
                'tools'          => 'Wazuh, Splunk, Wireshark, Nmap, Microsoft Excel',
                'skill'          => 'Computer Networking, Information System Audit, Cyber Security',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW064',
                'perusahaan_id'  => 'P020',
                'posisi'         => 'IT Governance & Compliance',
                'deskripsi'      => 'Mendukung pengelolaan kepatuhan keamanan informasi dan dokumentasi kebijakan IT di PT Sekuriti Siber Indonesia. Melakukan audit internal, gap analysis terhadap regulasi keamanan yang berlaku, dan menyusun laporan compliance secara berkala. Mendokumentasikan prosedur kepatuhan dan membantu penyusunan kebijakan keamanan informasi perusahaan.',
                'tools'          => 'Wazuh, Splunk, Wireshark, Nmap, Microsoft Excel',
                'skill'          => 'Information System Audit, IT Governance, Compliance',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW065',
                'perusahaan_id'  => 'P021',
                'posisi'         => 'Cybersecurity Analyst',
                'deskripsi'      => 'Menerapkan kebijakan keamanan informasi dan membantu pengelolaan risiko IT di PT PAL Indonesia sesuai standar yang berlaku. Melakukan analisis kerentanan, penyusunan dokumentasi kebijakan keamanan, dan peningkatan kesadaran keamanan bagi pengguna internal. Mendokumentasikan temuan audit dan menyusun rekomendasi peningkatan postur keamanan organisasi.',
                'tools'          => 'Wireshark',
                'skill'          => 'Information System Audit, IT Governance, Cyber Security',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW066',
                'perusahaan_id'  => 'P021',
                'posisi'         => 'Network Engineer',
                'deskripsi'      => 'Mengelola dan memantau jaringan serta server infrastruktur TI PT PAL Indonesia, termasuk troubleshooting dan pemeliharaan rutin. Melakukan konfigurasi perangkat jaringan Cisco atau Mikrotik, monitoring performa sistem, dan penanganan gangguan teknis. Mendokumentasikan topologi jaringan, konfigurasi perangkat, dan prosedur penanganan insiden.',
                'tools'          => 'Cisco, Mikrotik',
                'skill'          => 'Computer Networking, Operating System, Linux',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW067',
                'perusahaan_id'  => 'P021',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Menganalisis kebutuhan, merancang, mengimplementasikan, dan menguji aplikasi internal PT PAL Indonesia menggunakan Laravel dan MySQL. Menyusun dokumentasi teknis pengembangan aplikasi, membuat diagram alur sistem, dan berkoordinasi dengan pengguna untuk validasi fitur. Melakukan pengujian fungsional dan menyusun laporan testing sebelum aplikasi dirilis.',
                'tools'          => 'Laravel, MySQL, Git',
                'skill'          => 'Web Development, Software Testing, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW068',
                'perusahaan_id'  => 'P022',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Mengembangkan sistem informasi internal PT INKA menggunakan Laravel, termasuk implementasi fitur, pengelolaan database, dan integrasi antar modul. Melakukan analisis kebutuhan bersama pengguna internal, merancang solusi teknis, dan mendokumentasikan hasil pengembangan. Menyusun panduan teknis dan laporan progres pengembangan secara berkala.',
                'tools'          => 'Laravel, MySQL',
                'skill'          => 'Web Development, Data Analysis, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW069',
                'perusahaan_id'  => 'P022',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Mengolah dan menganalisis data operasional PT INKA menggunakan Looker Studio dan Excel untuk menghasilkan laporan insight yang relevan. Membuat dashboard visualisasi data, mengidentifikasi tren produksi, dan menyusun rekomendasi berbasis data untuk manajemen. Mendokumentasikan metodologi analisis dan memelihara template laporan standar perusahaan.',
                'tools'          => 'Looker Studio, Microsoft Excel',
                'skill'          => 'Data Analysis, Python, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW070',
                'perusahaan_id'  => 'P022',
                'posisi'         => 'IoT Engineer',
                'deskripsi'      => 'Mengaplikasikan teknologi IoT dan Digital Twin untuk pengembangan asset tracker dan simulasi layout penempatan mesin di PT INKA. Mengembangkan pipeline AI menggunakan Python untuk analisis data sensor dan prediksi kebutuhan pemeliharaan. Mendokumentasikan arsitektur sistem IoT dan menyusun laporan hasil implementasi digital twin.',
                'tools'          => 'TensorFlow',
                'skill'          => 'Machine Learning, Data Analysis, Python',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW071',
                'perusahaan_id'  => 'P023',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Mengembangkan dan memelihara perangkat lunak sistem informasi internal Atria Hotel Malang menggunakan teknologi web modern. Melakukan analisis kebutuhan pengguna hotel, implementasi fitur baru, dan pengelolaan database sistem hotel berbasis MySQL atau SQL Server. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk staf IT hotel.',
                'tools'          => 'MySQL, SQL Server',
                'skill'          => 'Software Engineering, Database Management, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW072',
                'perusahaan_id'  => 'P023',
                'posisi'         => 'Network Engineer',
                'deskripsi'      => 'Mengelola dan memantau infrastruktur jaringan Atria Hotel Malang, termasuk konfigurasi perangkat Cisco dan troubleshooting koneksi. Melakukan pemeliharaan rutin jaringan, monitoring trafik, dan memastikan ketersediaan layanan internet di seluruh area hotel. Mendokumentasikan topologi jaringan dan prosedur penanganan gangguan konektivitas.',
                'tools'          => 'Cisco',
                'skill'          => 'Computer Networking',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW073',
                'perusahaan_id'  => 'P023',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Mengolah data operasional hotel menggunakan Python dan Excel untuk menghasilkan laporan analitik pendukung keputusan manajemen Atria. Membuat dashboard visualisasi data occupancy, revenue, dan kepuasan tamu secara berkala. Mendokumentasikan metodologi analisis dan menyusun template laporan untuk keperluan evaluasi performa hotel.',
                'tools'          => 'Microsoft Excel',
                'skill'          => 'Data Analysis, Python',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW074',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web aplikasi produk PT Intelix Global Crossing menggunakan React atau JavaScript yang responsif dan interaktif. Melakukan integrasi dengan REST API backend, implementasi fitur sesuai spesifikasi, dan pengujian tampilan di berbagai browser. Membuat dokumentasi komponen frontend dan berpartisipasi dalam code review bersama tim.',
                'tools'          => 'React.js, Git',
                'skill'          => 'Web Development, REST API, JavaScript',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW075',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan backend dan REST API menggunakan PHP atau Laravel untuk mendukung produk digital PT Intelix Global Crossing. Merancang struktur database, mengimplementasikan logika bisnis, dan memastikan keamanan serta performa API. Mendokumentasikan endpoint API menggunakan Postman dan menyusun ERD sebagai referensi pengembangan.',
                'tools'          => 'Laravel, Node.js, MySQL, PostgreSQL, Git, Postman',
                'skill'          => 'Web Development, REST API, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW076',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'Quality Assurance (QA)',
                'deskripsi'      => 'Menyusun dan mengeksekusi test case untuk pengujian fungsional produk PT Intelix Global Crossing secara menyeluruh. Mendokumentasikan temuan bug dengan detail langkah reproduksi dan berkomunikasi dengan developer untuk proses perbaikan. Membuat laporan hasil QA dan memverifikasi perbaikan sebelum produk dirilis ke tahap berikutnya.',
                'tools'          => 'Postman, Git',
                'skill'          => 'Software Testing, Quality Assurance',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW077',
                'perusahaan_id'  => 'P024',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis kebutuhan sistem bersama klien dan tim developer PT Intelix Global Crossing untuk menghasilkan spesifikasi teknis yang akurat. Menyusun dokumen BRD, SRS, dan diagram UML sebagai acuan pengembangan, serta melakukan gap analysis terhadap sistem yang berjalan. Berkoordinasi dengan stakeholder untuk validasi spesifikasi dan memastikan kelengkapan dokumentasi proyek.',
                'tools'          => 'Git, Postman',
                'skill'          => 'System Analysis, Software Testing, Web Development',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW078',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi web end-to-end menggunakan PHP, Ruby, atau React.js di PT Dutakom Wibawa Putra termasuk R&D OLT Management Dashboard. Melakukan implementasi UI/UX, integrasi API REST atau GraphQL, dan pengujian menyeluruh dari sisi frontend maupun backend. Menyusun dokumentasi teknis fullstack dan melaporkan progres pengembangan secara rutin.',
                'tools'          => 'React.js, MySQL, PostgreSQL, GraphQL, Git',
                'skill'          => 'Web Development, REST API, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW079',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun prototipe endpoint REST atau GraphQL menggunakan PHP atau Ruby untuk sistem internal PT Dutakom Wibawa Putra. Merancang struktur database PostgreSQL atau MySQL, mengimplementasikan logika bisnis, dan mendokumentasikan endpoint API. Melakukan pengujian performa API dan menyusun catatan teknis untuk setiap iterasi pengembangan.',
                'tools'          => 'MySQL, PostgreSQL, GraphQL, Git',
                'skill'          => 'Web Development, REST API, PHP, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW080',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan prototipe antarmuka pengguna menggunakan React.js untuk sistem OLT Management Dashboard PT Dutakom. Melakukan integrasi dengan API backend, mengimplementasikan komponen UI yang modular, dan memastikan responsivitas tampilan. Membuat dokumentasi komponen React dan menyusun panduan penggunaan dashboard bagi tim internal.',
                'tools'          => 'React.js, Git',
                'skill'          => 'Web Development, REST API, JavaScript',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW081',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis requirement dan menyusun dokumen BRD atau FSD untuk proyek pengembangan sistem di PT Dutakom Wibawa Putra. Membuat diagram UML, mendokumentasikan alur bisnis, dan berkoordinasi dengan tim teknis untuk memastikan spesifikasi dapat diimplementasikan. Melakukan gap analysis dan menyusun rekomendasi peningkatan sistem yang berjalan.',
                'tools'          => 'Git',
                'skill'          => 'System Analysis, Project Management',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW082',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'IT Support Specialist',
                'deskripsi'      => 'Mendukung kegiatan helpdesk harian, pemeliharaan workstation, jaringan, dan sistem surveilance di PT Dutakom Wibawa Putra. Membantu implementasi kebijakan keamanan sesuai standar ISO 27001 dan manajemen mutu perusahaan. Mendokumentasikan prosedur operasional infrastruktur dan menyusun laporan insiden teknis secara berkala.',
                'tools'          => 'Cisco, ISO 27001',
                'skill'          => 'Computer Networking, Operating System, IT Governance',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW083',
                'perusahaan_id'  => 'P025',
                'posisi'         => 'Network Engineer',
                'deskripsi'      => 'Melakukan manajemen kabel, interkoneksi perangkat, dan instalasi rack di data center PT Dutakom Wibawa Putra. Mendukung kegiatan commissioning perangkat jaringan, pemeliharaan fisik infrastruktur, dan dokumentasi inventaris data center. Menyusun laporan kondisi infrastruktur dan membantu proses pengadaan perangkat sesuai kebutuhan operasional.',
                'tools'          => 'Cisco',
                'skill'          => 'Computer Networking',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW084',
                'perusahaan_id'  => 'P026',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Mengembangkan dan memelihara aplikasi web klien CV Harsyad Teknologi dari tahap analisa kebutuhan hingga deployment menggunakan PHP atau Laravel. Melakukan integrasi fitur, pengelolaan database MySQL, dan pengujian fungsional aplikasi sebelum rilis. Mendokumentasikan perubahan sistem dan menyusun panduan teknis untuk tim dan klien.',
                'tools'          => 'Laravel, React.js, MySQL, Git, Postman, Figma',
                'skill'          => 'Web Development, System Analysis, REST API, Software Testing, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW085',
                'perusahaan_id'  => 'P026',
                'posisi'         => 'Software Engineer',
                'deskripsi'      => 'Terlibat dalam seluruh siklus pengembangan perangkat lunak di CV Harsyad Teknologi, mulai dari perancangan arsitektur hingga release aplikasi. Melakukan analisis kebutuhan, implementasi fitur backend dan frontend, serta pengujian sistem secara menyeluruh. Menyusun dokumentasi teknis, test report, dan changelog untuk setiap versi yang dirilis.',
                'tools'          => 'Laravel, React.js, MySQL, Git, Postman, Figma',
                'skill'          => 'Software Engineering, System Analysis, REST API, Software Testing, Web Development, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 6,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW086',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'Backend Developer',
                'deskripsi'      => 'Membangun layanan API dan logika bisnis aplikasi web klien DOT Indonesia menggunakan Laravel atau Node.js. Merancang dan mengimplementasikan struktur database, memastikan keamanan endpoint, dan mengoptimalkan performa query. Mendokumentasikan API menggunakan Postman dan menyusun catatan teknis perubahan backend.',
                'tools'          => 'Laravel, Node.js, MySQL, PostgreSQL, Postman',
                'skill'          => 'Web Development, REST API, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW087',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'Frontend Developer',
                'deskripsi'      => 'Mengembangkan antarmuka web interaktif menggunakan React atau Vue.js untuk proyek klien DOT Indonesia yang responsif dan accessible. Melakukan integrasi komponen frontend dengan REST API, mengimplementasikan state management, dan mengoptimalkan performa rendering. Membuat dokumentasi komponen dan melakukan code review bersama tim frontend.',
                'tools'          => 'React.js, Vue.js',
                'skill'          => 'Web Development, REST API, JavaScript',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW088',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan aplikasi web fullstack end-to-end di DOT Indonesia menggunakan React atau Vue untuk frontend dan Laravel atau Node.js untuk backend. Merancang arsitektur sistem, melakukan integrasi layanan, dan memastikan kualitas kode melalui pengujian yang menyeluruh. Menyusun dokumentasi teknis lengkap dan berpartisipasi aktif dalam sprint planning tim.',
                'tools'          => 'Laravel, Node.js, React.js, Vue.js, MySQL, PostgreSQL',
                'skill'          => 'Web Development, REST API, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW089',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'AI Engineer',
                'deskripsi'      => 'Mengembangkan model dan pipeline AI atau ML untuk kebutuhan klien DOT Indonesia menggunakan Python dan TensorFlow atau PyTorch. Melakukan preprocessing data, eksperimen model, evaluasi performa, dan integrasi hasil model ke dalam aplikasi. Mendokumentasikan eksperimen, parameter model, dan menyusun laporan rekomendasi pengembangan AI.',
                'tools'          => 'TensorFlow, PyTorch',
                'skill'          => 'Machine Learning, Data Mining, Python',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW090',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Melakukan analisis kebutuhan sistem, menyusun dokumen SRS dan BRD, serta membuat diagram UML untuk proyek klien DOT Indonesia. Melakukan gap analysis, berkoordinasi dengan developer dan klien untuk validasi spesifikasi, dan memastikan dokumentasi teknis lengkap dan akurat. Memantau kesesuaian implementasi dengan spesifikasi yang telah disepakati.',
                'tools'          => '-',
                'skill'          => 'System Analysis, System Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW091',
                'perusahaan_id'  => 'P027',
                'posisi'         => 'UI/UX Designer',
                'deskripsi'      => 'Merancang antarmuka pengguna aplikasi klien DOT Indonesia menggunakan Figma, dari wireframe hingga prototipe interaktif siap handoff. Melakukan riset pengguna, menyusun user flow, design system, dan memastikan konsistensi visual antar halaman. Mendokumentasikan panduan desain dan berkolaborasi dengan tim frontend dalam proses implementasi.',
                'tools'          => 'Figma',
                'skill'          => 'UI/UX Design, System Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW092',
                'perusahaan_id'  => 'P028',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Melakukan analisis data untuk mendukung pengambilan keputusan bisnis Oyitok Group menggunakan SQL dan Python. Membuat dashboard visualisasi menggunakan Power BI atau Looker Studio dan menyusun laporan insight secara berkala. Mendokumentasikan metodologi analisis dan memberikan rekomendasi berbasis data kepada manajemen.',
                'tools'          => 'Microsoft Excel, Power BI, Looker Studio, MySQL',
                'skill'          => 'Data Analysis, SQL, Python',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW093',
                'perusahaan_id'  => 'P028',
                'posisi'         => 'System Administrator',
                'deskripsi'      => 'Mengelola dan memelihara sistem administrasi digital Oyitok Group, termasuk pengelolaan database, konfigurasi sistem, dan penanganan akses pengguna. Melakukan pemeliharaan rutin infrastruktur IT, monitoring performa sistem, dan memastikan ketersediaan layanan berjalan optimal. Mendokumentasikan prosedur administrasi sistem dan menyusun laporan status infrastruktur.',
                'tools'          => 'Microsoft Excel, MySQL',
                'skill'          => 'Database Management, System Analysis, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW094',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'Fullstack Developer',
                'deskripsi'      => 'Mengembangkan fitur backend dan frontend aplikasi web CV DB KLIK menggunakan React.js, Node.js, atau Laravel sesuai kebutuhan proyek. Melakukan integrasi API, pengelolaan database MySQL, debugging, dan unit testing untuk memastikan kualitas kode. Mendokumentasikan perubahan fitur dan berpartisipasi dalam sprint review bersama tim.',
                'tools'          => 'React.js, Node.js, Laravel, MySQL, Git',
                'skill'          => 'Web Development, REST API, Software Testing, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW095',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'UI/UX Designer',
                'deskripsi'      => 'Merancang wireframe, user flow, dan prototipe interaktif untuk produk digital CV DB KLIK menggunakan Figma atau Adobe XD. Melakukan riset kebutuhan pengguna, menyusun design system, dan memastikan konsistensi tampilan antar halaman aplikasi. Mendokumentasikan panduan desain dan berkolaborasi dengan tim developer dalam proses implementasi.',
                'tools'          => 'Figma, Adobe XD',
                'skill'          => 'UI/UX Design, System Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW096',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'System Analyst',
                'deskripsi'      => 'Menganalisis kebutuhan sistem, menyusun dokumen UML, BRD atau FRD, dan melakukan gap analysis untuk proyek CV DB KLIK. Berkoordinasi dengan tim teknis dan klien untuk memvalidasi spesifikasi sistem dan memastikan kelengkapan dokumentasi teknis. Melakukan quality assurance terhadap kesesuaian implementasi dengan spesifikasi yang telah disepakati.',
                'tools'          => 'Git',
                'skill'          => 'System Analysis, System Design',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW097',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'Data Analyst',
                'deskripsi'      => 'Melakukan pembersihan, pengolahan, dan visualisasi data operasional CV DB KLIK menggunakan SQL, Python, Tableau, atau Power BI. Menganalisis tren data, menyusun dashboard laporan, dan memberikan rekomendasi insight kepada manajemen secara berkala. Mendokumentasikan proses analisis dan memelihara template laporan standar untuk keperluan reporting.',
                'tools'          => 'Tableau, Power BI, Looker Studio, MySQL',
                'skill'          => 'Data Analysis, SQL, Python',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'lowongan_id'    => 'LW098',
                'perusahaan_id'  => 'P029',
                'posisi'         => 'Web Developer',
                'deskripsi'      => 'Mengembangkan dan memelihara website klien CV DB KLIK menggunakan React.js, Node.js, atau Laravel dengan fokus pada performa dan kemudahan penggunaan. Melakukan implementasi fitur, integrasi REST API, dan pengujian lintas browser untuk memastikan kualitas website. Mendokumentasikan perubahan kode dan menyusun panduan teknis untuk pengelola website.',
                'tools'          => 'React.js, Node.js, Laravel, MySQL, Git',
                'skill'          => 'Web Development, REST API, PHP, JavaScript, SQL',
                'ipk_min'        => 3.0,
                'periode'        => 5,
                'insentif'       => 'Paid',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        DB::table('lowongan_models')->insert($lowongan);
    }
}