<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PerusahaanSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $perusahaan = [
            [
                'perusahaan_id'     => 'P001',
                'nama_perusahaan'   => 'PT Indoprima Gemilang',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Indoprima Gemilang berdiri sejak 1976 di Surabaya, merupakan perusahaan manufaktur komponen otomotif (wiring harness, kabel baterai, saklar kombinasi, lapisan rem, dll) untuk berbagai pabrikan internasional seperti Daihatsu, Honda, Yamaha, Isuzu, Mitsubishi, dan lainnya. Bagian dari Indoprima Group.',
                'lokasi'            => 'Jl. Margomulyo Komp. Gardu Induk PLN No.5, Tandes, Surabaya, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P002',
                'nama_perusahaan'   => 'PT Link Apisindo Media & Dinas LH Kota Batu',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Link Apisindo Media adalah perusahaan IT di Malang yang bergerak di bidang penyediaan akses internet dan pengembangan sistem informasi. Berkolaborasi dengan Dinas Lingkungan Hidup Kota Batu untuk mengembangkan Sistem Informasi Penataan dan Penaatan (SIPP) lingkungan hidup.',
                'lokasi'            => 'Jl. Bunga Coklat No.22, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P003',
                'nama_perusahaan'   => 'PT Link Apisindo Media & Dinas Kominfo Jatim',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Link Apisindo Media berkolaborasi dengan Dinas Kominfo Jawa Timur untuk mengembangkan Platform Satu Peta Jawa Timur, sistem pemetaan dan visualisasi data spasial skala provinsi berbasis WebGIS.',
                'lokasi'            => 'Jl. Bunga Coklat No.22, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P004',
                'nama_perusahaan'   => 'PT ARM Solusi',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT ARM Solusi berdiri sejak 2001, merupakan perusahaan IT consulting di Jakarta dengan spesialisasi Django, Python, PostgreSQL, Odoo, dan Office Automation. Berfokus pada solusi Secure, Workflow, Collaboration & Integration untuk berbagai klien korporat.',
                'lokasi'            => 'Kawasan Epicentrum Walk, Office Suite A52, Jl. H.R. Rasuna Said, Jakarta Selatan, DKI Jakarta',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P005',
                'nama_perusahaan'   => 'Sarastya Agility Innovations',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'Sarastya Agility Innovations adalah perusahaan konsultan bisnis & teknologi di Malang yang berfokus pada Business Agility, Business Process Management (BPM), dan pengembangan sistem ERP-BPM. Membantu organisasi membangun tim yang lincah melalui pendekatan Agile dan Scrum.',
                'lokasi'            => 'Terra Building, Jl. Terusan Candi Mendut No.9B, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P006',
                'nama_perusahaan'   => 'PT Time Door Indonesia',
                'jenis_perusahaan'  => 'swasta',
                'profil_perusahaan' => 'PT Timedoor Indonesia adalah startup IT yang didirikan tahun 2014 di Bali oleh entrepreneur Jepang. Menyediakan jasa web development, pengembangan aplikasi mobile, IoT, UI/UX, outsourcing IT, dan pendidikan teknologi (Timedoor Academy). Telah melayani 500+ klien dengan 150+ karyawan.',
                'lokasi'            => 'Jl. Tukad Yeh Aya IX No.46, Renon, Denpasar Selatan, Kota Denpasar, Bali',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P007',
                'nama_perusahaan'   => 'PT Maxchat Inovasi Indonesia',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Maxchat Inovasi Indonesia adalah perusahaan teknologi di Malang, merupakan Meta Official Business Partner untuk layanan WhatsApp Business API di Indonesia sejak 2020. Menyediakan solusi Omnichannel CRM, chatbot, dan integrasi WhatsApp API untuk berbagai industri.',
                'lokasi'            => 'Jl. Candi Sawentar No.E209, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P008',
                'nama_perusahaan'   => 'Politeknik Batu',
                'jenis_perusahaan'  => 'instansi pendidikan',
                'profil_perusahaan' => 'Politeknik Batu adalah perguruan tinggi vokasi yang berlokasi di Batu, Jawa Timur, berfokus pada pendidikan vokasional berbasis praktik. Membutuhkan mahasiswa magang untuk mendukung pengembangan dan pengujian aplikasi internal.',
                'lokasi'            => 'Kota Batu, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P009',
                'nama_perusahaan'   => 'Ariverse Studio (PT Studio Karya Semesta)',
                'jenis_perusahaan'  => 'swasta',
                'profil_perusahaan' => 'Ariverse Studio adalah studio pengembangan game di Malang yang berfokus pada produksi game PC, Console, dan Mobile. Dipimpin oleh CEO Muhammad Ali Zulfikar, studio ini juga mengerjakan VR/AR, gamified learning, dan aplikasi berbasis web untuk klien.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P010',
                'nama_perusahaan'   => 'Humas POLINEMA',
                'jenis_perusahaan'  => 'instansi pendidikan',
                'profil_perusahaan' => 'Humas Politeknik Negeri Malang (Polinema) adalah unit yang mengelola komunikasi publik, media sosial, dan data institusional Polinema. Membutuhkan mahasiswa magang untuk menganalisis data digital media dan social media analytics.',
                'lokasi'            => 'Jl. Soekarno Hatta No.9, Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P011',
                'nama_perusahaan'   => 'PT Alfath Corporation',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Alfath Corporation adalah perusahaan yang bergerak di bidang pengembangan solusi digital berbasis AI, chatbot, dan otomasi proses bisnis. Fokus pada teknologi fullstack modern termasuk integrasi n8n, WebSocket, dan AI chatbot.',
                'lokasi'            => 'Jl. Kalpataru No.145A, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P012',
                'nama_perusahaan'   => 'PT UTERO KREATIF INDONESIA',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Utero Kreatif Indonesia (Utero Technology) adalah perusahaan teknologi di Malang yang mengembangkan solusi digital berbasis web dan mobile. Berfokus pada efisiensi, skalabilitas, dan pendekatan berbasis data dalam pengembangan produk teknologi.',
                'lokasi'            => 'Jl. Bantaran 1 No.25, Tulusrejo, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P013',
                'nama_perusahaan'   => 'The Himana Hotel & Mall Malang City Point',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'The Himana Hotel adalah hotel bintang di Malang City Point yang menyediakan layanan perhotelan premium. Membuka program magang (OJT) untuk mahasiswa/pelajar yang ingin mendapatkan pengalaman langsung di industri hospitality.',
                'lokasi'            => 'Malang City Point, Jl. Terusan Dieng No.31, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P014',
                'nama_perusahaan'   => 'Wakil Direktur 4 Politeknik Negeri Malang',
                'jenis_perusahaan'  => 'instansi pendidikan',
                'profil_perusahaan' => 'Wakil Direktur 4 Politeknik Negeri Malang membidangi kerjasama dan pengembangan institusi. Membutuhkan mahasiswa untuk mendukung pengembangan sistem web, manajemen data dokumen kerjasama, dan analitik data.',
                'lokasi'            => 'Jl. Soekarno Hatta No.9, Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P015',
                'nama_perusahaan'   => 'PT Rekaindo Global Jasa',
                'jenis_perusahaan'  => 'swasta',
                'profil_perusahaan' => 'PT Rekaindo Global Jasa (REKA) berdiri 1998 di Madiun, merupakan perusahaan konsultan engineering dan support komponen kereta api. Dimiliki bersama PT INKA, Nippon Sharyo Ltd, Sumitomo Corporation, dan KOPINKA. Bergerak di bidang desain 3D, panel kontrol elektrik, dan komponen perkeretaapian.',
                'lokasi'            => 'Jl. Candi Sewu No.30, Kel. Madiun Lor, Kec. Manguharjo, Kota Madiun, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P016',
                'nama_perusahaan'   => 'PT JST Indonesia',
                'jenis_perusahaan'  => 'swasta',
                'profil_perusahaan' => 'PT JST Indonesia adalah perusahaan manufaktur yang bergerak dalam pembuatan komponen elektronik dan wiring harness untuk industri otomotif. Membuka magang untuk mendukung proyek digitalisasi, otomatisasi, dan AI di internal perusahaan.',
                'lokasi'            => 'Kawasan Industri MM2100, Jl. Irian I Blok GG No.4, Cikarang Barat, Bekasi, Jawa Barat',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P017',
                'nama_perusahaan'   => 'PT Green Energi Utama',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Green Energi Utama adalah perusahaan yang bergerak di bidang energi terbarukan. Membuka program magang bagi mahasiswa dari jurusan yang relevan untuk mendukung kegiatan operasional dan pengembangan perusahaan.',
                'lokasi'            => 'Pergudangan Tanrise K-Walk, Jl. Raya Karanglo No.A-2, Banjararum, Singosari, Kab. Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P018',
                'nama_perusahaan'   => 'UPA Bahasa Polinema',
                'jenis_perusahaan'  => 'instansi pendidikan',
                'profil_perusahaan' => 'UPA Bahasa Politeknik Negeri Malang adalah unit pelayanan bahasa yang menyediakan layanan kursus bahasa, tes TOEIC/TOEFL/IELTS, dan jasa terjemahan. Membutuhkan mahasiswa untuk pengembangan website dan pembuatan konten digital.',
                'lokasi'            => 'Jl. Soekarno Hatta No.9, Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P019',
                'nama_perusahaan'   => 'PT Peruri Wira Timur',
                'jenis_perusahaan'  => 'BUMN',
                'profil_perusahaan' => 'PT Peruri Wira Timur (PWT) berdiri 2011 di Surabaya, merupakan anak perusahaan Perum Peruri (BUMN) yang bergerak di bidang pencetakan dokumen dan produk sekuriti non-uang (ijazah, dokumen perizinan, dll). Kepemilikan Peruri 76%, berlokasi di Jl. Ahmad Yani Surabaya.',
                'lokasi'            => 'Jl. Ahmad Yani, Surabaya, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P020',
                'nama_perusahaan'   => 'PT Sekuriti Siber Indonesia',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Sekuriti Siber Indonesia (Nemo Security) adalah perusahaan yang bergerak di bidang keamanan siber, dengan layanan utama Security Operations Center (SOC), compliance/kepatuhan, dan monitoring keamanan jaringan menggunakan SIEM dan teknologi terkait.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P021',
                'nama_perusahaan'   => 'PT PAL Indonesia (Persero)',
                'jenis_perusahaan'  => 'BUMN',
                'profil_perusahaan' => 'PT PAL Indonesia adalah BUMN galangan kapal terbesar di Indonesia, berdiri 1980 (cikal bakal sejak 1939). Memproduksi kapal perang, kapal niaga, kapal selam, serta produk energi & elektrifikasi. Berlokasi di Surabaya, produknya telah diekspor ke berbagai negara.',
                'lokasi'            => 'Jl. Ujung, Ujung, Semampir, Kota Surabaya, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P022',
                'nama_perusahaan'   => 'PT Industri Kereta Api / PT INKA (Persero)',
                'jenis_perusahaan'  => 'BUMN',
                'profil_perusahaan' => 'PT Industri Kereta Api (INKA) berdiri 1981 di Madiun, merupakan BUMN manufaktur kereta api terintegrasi pertama dan terbesar di Asia Tenggara. Memproduksi lokomotif, kereta penumpang, KRL, LRT, dan berbagai gerbong. Produk telah diekspor ke Bangladesh, Filipina, Malaysia, Thailand, dll.',
                'lokasi'            => 'Jl. Yos Sudarso No.71, Madiun, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P023',
                'nama_perusahaan'   => 'Atria Hotel Malang',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'Atria Hotel Malang adalah hotel bintang 4 di Malang yang menyediakan layanan perhotelan premium. Departemen IT hotel mencakup pengelolaan software, jaringan, dan data analytics untuk mendukung operasional hotel.',
                'lokasi'            => 'Jl. Cengger Ayam No.1, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P024',
                'nama_perusahaan'   => 'PT Intelix Global Crossing',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Intelix Global Crossing adalah perusahaan IT di Malang yang bergerak dalam pengembangan produk digital dan solusi teknologi informasi untuk berbagai klien. Mengerjakan proyek end-to-end dari analisis bisnis hingga deployment.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P025',
                'nama_perusahaan'   => 'PT Dutakom Wibawa Putra',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'PT Dutakom Wibawa Putra adalah perusahaan penyedia layanan teknologi informasi dan komunikasi (ICT) di Surabaya, dengan layanan internet, data center, dan solusi enterprise. Mengerjakan berbagai proyek berbasis OLT Management, REST API, dan infrastruktur IT.',
                'lokasi'            => 'Surabaya, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P026',
                'nama_perusahaan'   => 'CV Harsyad Utama (Harsyad Teknologi)',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'CV Harsyad Utama / Harsyad Teknologi adalah perusahaan software house di Malang yang mengerjakan pengembangan aplikasi internal maupun proyek eksternal berbasis web. Mahasiswa terlibat dalam proses full-cycle dari analisa kebutuhan hingga release aplikasi.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P027',
                'nama_perusahaan'   => 'DOT Indonesia',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'DOT Indonesia adalah perusahaan software house terkemuka di Indonesia yang bergerak dalam pengembangan aplikasi web, mobile, dan AI. Telah mengerjakan berbagai proyek digital untuk klien nasional dan internasional.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P028',
                'nama_perusahaan'   => 'Oyitok Group',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'Oyitok Group adalah perusahaan yang sedang mengembangkan sistem digitalisasi administrasi dan analitik data internal. Membutuhkan mahasiswa dengan kemampuan data analysis untuk mendukung transformasi digital perusahaan.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'perusahaan_id'     => 'P029',
                'nama_perusahaan'   => 'CV DB KLIK',
                'jenis_perusahaan'  => 'swasta nasional',
                'profil_perusahaan' => 'CV DB KLIK (DB Group) adalah perusahaan IT yang berdiri sejak tahun 2000 di bidang penjualan alat IT dan solusi IT (#OneStopITSolution). Membuka program magang untuk berbagai posisi IT development dan analitik.',
                'lokasi'            => 'Malang, Jawa Timur',
                'web_career'        => null,
                'logo'              => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        DB::table('perusahaan')->insert($perusahaan);
    }
}